### ISSUE TITLE
NPM Including Duplicate Dependencies

### ISSUE THREAD

**Issue by mwagz** [github/licensed#105]
I broke it. 😔 
---
My recent work on `Licensed::Source::NPM` is causing cache entries for instances of multiple versions of the dependency. This was not the case prior to that update. Currently looking into alternatives more closely aligned to `Licensed::Source::Go`.

**Comment by mlinksva** [comment]
This sounds like intended behavior introduced recently https://github.com/github/licensed/pull/89

**Comment by mwagz** [comment]
I _just_ came to that realization @mlinksva. Lol. Thanks for reducing my panic. 😅 My project was previously using v1.1.0 so I was a little worried when I saw more licensed issues pop up.
