### ISSUE TITLE
Please add support for pip

### ISSUE THREAD

**Issue by gposton** [github/licensed#11]
Please add support for pip

**Comment by jonabc** [comment]
:wave: Hi @gposton pip support would be great!

Unfortunately I'm busy at the moment and can't give you any sort of timeframe for when I'd be able to implement it.

If you'd like to see support for pip sooner, 👍 to opening a PR with an implementation and I'd gladly take a look!

**Comment by jonabc** [comment]
Fixed via https://github.com/github/licensed/pull/32, released as part of `licensed-1.1.0`
