### ISSUE TITLE
Proposal: Add a gradle dependency source

### ISSUE THREAD

**Issue by jandersson-svt** [github/licensed#122]
It would be great to also be able to drop licensed in a project with a gradle build and get licensed information as with the other dependency sources.

(I might have the time to investigate in starting such an implementation)

**Comment by jonabc** [comment]
@jandersson-svt :wave: FYI there is a close-to-done solution over in https://github.com/github/licensed/pull/150

**Comment by jonabc** [comment]
https://github.com/github/licensed/pull/150 has been merged, gradle support will be included in the next release.

**Comment by jandersson-svt** [comment]
Amazing, will look into it. BTW Started an implementation that was almost done, and then other projects like a baby got in the way:) so I'm glad to see it done. Thanks
