### ISSUE TITLE
Include license information in standalone distribution

### ISSUE THREAD

**Issue by jclem** [github/licensed#155]
Currently, the standalone distribution of licensed only contains the licensed binary itself. It would be helpful if the tarball included the license file, as well as license information for licensed's dependencies.

**Comment by mlinksva** [comment]
Ideal thing would be a `NOTICE` file which contains dependencies and license info that licensed enumerates for itself. 😄 🐶 🥘

**Comment by jonabc** [comment]
> Ideal thing would be a NOTICE file which contains dependencies and license info that licensed enumerates for itself.

👍 dogfooding!  What would you recommend the `NOTICE` file contents looking like in terms of data and formatting?

**Comment by jonabc** [comment]
For now, I've updated the 2.0.1 release archives to contain ruby's license.txt, licensed's own LICENSE and README.md, and the *.dep.yml files from running licensed on itself.

```
➜  licensed git:(master) ✗ tar -tzf licensed-2.0.1-darwin-x64.tar.gz
./licensed
./meta/
./meta/LICENSE
./meta/README.md
./meta/.licenses/
./meta/ruby/
./meta/ruby/license.txt
./meta/.licenses/bundler/
./meta/.licenses/bundler/public_suffix.dep.yml
./meta/.licenses/bundler/dotenv.dep.yml
./meta/.licenses/bundler/addressable.dep.yml
./meta/.licenses/bundler/thor.dep.yml
./meta/.licenses/bundler/octokit.dep.yml
./meta/.licenses/bundler/licensee.dep.yml
./meta/.licenses/bundler/multipart-post.dep.yml
./meta/.licenses/bundler/faraday.dep.yml
./meta/.licenses/bundler/pathname-common_prefix.dep.yml
./meta/.licenses/bundler/rugged.dep.yml
./meta/.licenses/bundler/sawyer.dep.yml
./meta/.licenses/bundler/tomlrb.dep.yml
./meta/.licenses/bundler/bundler.dep.yml
```

I'll use this issue to track package scripting changes to make this automatic in the future.  Should previous releases be updated as well?

**Comment by mlinksva** [comment]
Iff it's easy to update the previous releases, yes.

Regarding `NOTICE` formatting, I don't know of existing conventions off the top of my head, other than ad hoc concatenation of license notices sometimes with ad hoc metadata. So simple concatenation would be a reasonable first implementation.

**Comment by jonabc** [comment]
@mlinksva ah, so I'm confused now. Should I ship release packages with a breakdown of files like I posted a few days ago ☝️ , or a `NOTICES` file, or something else?

As for a concatenation of content in `NOTICES`, it should be the following?  Does ordering matter?
- the ruby license
- licensed's own `LICENSE` and `README.md`
- the license and notice texts for each dependency

**Comment by mlinksva** [comment]
Sorry for being confusing. Let's just stick with the breakdown you posted a few days ago at https://github.com/github/licensed/issues/155#issuecomment-478154410

**Comment by jonabc** [comment]
@mlinksva alright I think I've hit a bit of a blocking problem on this in that the version of licensed's dependencies that are `bundle install`'d in the squashed filesystem are not necessarily the same dependency versions that are `bundle install`'d in the git repository where the packaging commands are being run.

Not sure how to get past that right now, it affects being able to manually grab the license metadata as well as an automated solution.

Does not having dependency license info block being able to put out new releases?

**Comment by mlinksva** [comment]
Yes, I'd like to see that fixed before a new binary release is put out.

This is beyond the limit of my very weak understanding of bundler, but I'm curious what causes the discrepancy -- https://github.com/github/licensed/blob/c8aeac38d523ed0e3830452520337b67ccf54d09/docker/Dockerfile.build-linux#L1 (Ruby 2.4) leads to different versions being used of some gems?

**Comment by jonabc** [comment]
I'm struggling on how to explain this, so apologies if I get too verbose here.

If I understand `ruby-packer` properly, the executable is a squashed file system + an executable script that automatically unpacks the squashed file system, runs a command in a ruby context limited to the scope of that unpacked file system, then deletes the unpacked file system.

As part of building the squashed file system, the licensed gem folder is copied into the directory that gets squashed and a limited-scope ruby/bundler installation in that folder `bundle install`s the gem.  That happens separately from any action I as a developer may take in the local git repo I work in, so the dependent gems that are installed in the squashed filesystem may not be the same gems that are installed from my local git repo.

To get the dependencies that are installed in the squashed file system I need to be able to run `licensed` in the context of that file system and not in the context of the host OS.
