### ISSUE TITLE
Proposal: Add a feature to suggest if any licenses are incompatible

### ISSUE THREAD

**Issue by jandersson-svt** [github/licensed#161]
While not attempting to be a lawyer, it would be a good help if, in licensed, there was a function to give a hint if there are any problems between a common licenses.

For example: licensed check-compatibility

, and some warnings would be outputted after checking the licenses. One such implementation is here, https://github.com/librariesio/license-compatibility/tree/master/lib/license and as this is under MIT, one could use a bit of that metadata and code, and implement it into licensed.

**Comment by jonabc** [comment]
@jandersson-svt :wave: sorry I haven't responded to this sooner.

I think this would make more sense as functionality in https://github.com/licensee/licensee which provides the underlying license detection logic.  Can you open this issue in that repo instead?

I'm going to close this for now - if you feel that it really needs to be solved here, or if it's not something that the maintainers of licensee feel should be in that project then please reopen and we can figure something out 🙇
