### ISSUE TITLE
This software is really cool. Thankyou

### ISSUE THREAD

**Issue by ghuntley** [github/licensed#169]
https://twitter.com/GeoffreyHuntley/status/1138723566352883713?s=09

I've got some thoughts about potential things to see in the future. Maybe something like

- iterate through all folders and discover LICENSES within a folder 
- iterate through each file and search the header of that file for a SPDX identifier
- extract licenses from a nixos/nixpkgs expression

The first two would be helpful for monorepos.

**Comment by jonabc** [comment]
:wave: @ghuntley thanks! I'm glad you find it useful 🙇  I would love to hear more details about your use cases and what type of code you're thinking about - languages, frameworks, etc...

> The first two would be helpful for monorepos.

> - iterate through all folders and discover LICENSES within a folder

Licensed already has support for monorepos though it handles what it calls ["apps" ](https://github.com/github/licensed/blob/master/docs/configuration.md#applications).  With apps you can configure dependency sourcing for multiple subfolders in a repo from a single configuration file.

> - iterate through each file and search the header of that file for a SPDX identifier

Licensed also has support for [manifested dependency sourcing](https://github.com/github/licensed/blob/master/docs/sources/manifests.md), where the project owner is responsible for providing licensed with a list of files (or glob-ish expressions) for configured apps.  This dependency source detects license content from multiline c-style header comments.

Is there more detection that you're interested in?

> - extract licenses from a nixos/nixpkgs expression

Can you provide some examples of what this looks like?  It's not overly complicated to add [new dependency sources](), if you want to try putting something together I'd be happy to review it and get it into a future version.  Alternatively if you would like to open an issue requesting it as a new dependency source I, or another friendly OSS contributor, can take a look when possible.

Thanks again!

**Comment by jonabc** [comment]
Closing as there hasn't been any followup since June.  Please feel free to add any additional comments on how we can make the tool better.
