### ISSUE TITLE
Include package manager content in cached record

### ISSUE THREAD

**Issue by jonabc** [github/licensed#189]
As referenced in [this comment](https://github.com/github/licensed/pull/188#discussion_r327885310), matched package manager content isn't included in the cached record that get's persisted in a repo.

Excluding matched package manager content has been around since the [initial public release of the tool](https://github.com/github/licensed/blob/1.0.0/lib/licensed/dependency.rb#L80-L85) (and earlier IIRC).  That could be confusing though since the package manager is included when determining the value set to the cached `license` field.

Should the package manager content be included in cached files, and if so is it enough to include the raw text, e.g.
```yaml
licenses:
- sources: 'licensed.gemspec'
  text: 'spec.license       = "MIT"'
```

**Comment by mlinksva** [comment]
I suspect the reason a package manager assertion wasn't included is that preserving the package manager annotation is not required by any open source license (preserving license text is by nearly all) so there was no hard requirement (for a license compliance oriented BOM) motivating its inclusion.

Including it might be a little helpful when looking at cached files so as to not have to dig into a project to double check where the top level license is coming form. So I think I'm 👍 on caching it.

**Comment by jonabc** [comment]
@mlinksva @benbalter :wave: a few questions maybe you could help out with that would help determine how best to implement this.  I don't have enough legal or detailed OSS licensing knowledge to know how licensed should balance ease of use vs legal requirements.

1. If the only license content found is from a package manager file's license assertion should `license status` fail the corresponding dependency?

   If only package manager content is found, we could
   1. pass the dependency, as there was some determination of the license of the dependency based on the package manager metadata
   2. fail the dependency, as there was no legal text included in the dependency despite the package manager metadata
   3. pass the dependency based on package manager metadata, but add a warning that the dependency didn't contain any license text

2. It looks like `Licensee` provides a list of conditions associated with each license.  Would it make sense to only fail a dependency when there's a license, no license text, and a license condition of `include-copyright`?

3. Do you know if there would be any legal issue with including the package manager content in the `licenses` field, represented as license text?

   If so, we could add the package manager content as a separate field entirely
```yaml
name: dependency
version: 1.0.0
license: mit
licenses: []
notices: []
package_manager:
  source: dependency.gemspec
  license: mit
```

**Comment by mlinksva** [comment]
1. ii is probably the most reasonable default
2. reasonable idea, though probably not saving much work for users (licenses without `include-copyright` are relatively rare
3. don't think it matters what the field is named

**Comment by jonabc** [comment]
@mlinksva thanks for taking a look 🙇 

> 1. ii is probably the most reasonable default

🤔 that's the current behavior that I was hoping we could alleviate some pain from.  Just in case it wasn't clear, because I don't think I mentioned it 🤦‍♂, I was referring to the error when license text isn't found.  It seems odd that we'd classify something based on the license from the package manager but then fail it for not having license text.

> 2. reasonable idea, though probably not saving much work for users (licenses without include-copyright are relatively rare

👍 I'll open a separate issue for that and keep it in the backlog in case someone else wants to try it out or I get some extra time.

> 3. don't think it matters what the field is named

It's less about what the field is named, and more about how we handle the package manager content.  If we want to consider package manager content as "license text" then we can include it under the `licenses:` field.  If we want to do anything else with it then it would be easier to separate it out into its own field.

**Comment by sergey-alekseev** [comment]
Would be great to support multiple licenses in gem spec. E.g. https://github.com/SixArm/sixarm_ruby_unaccent/blob/f8f0819dfd433bce8f9e3862b2a8192fa11de476/sixarm_ruby_unaccent.gemspec#L13:  
`s.licenses = ["Apache-2.0", "Artistic-2.0", "BSD-3-Clause", "CC-BY-NC-SA-4.0", "AGPL-3.0", "EPL-1.0", "GPL-2.0", "GPL-3.0", "LGPL-3.0", "MIT", "MPL-2.0", "Ruby"]`

**Comment by jonabc** [comment]
@sergey-alekseev :+1: how does the licensee gem classify the project when run from cli?  As long as it is returning all appropriate information we can support it in licensed.

**Comment by sergey-alekseev** [comment]
@jonabc  

```
$ licensee detect https://github.com/SixArm/sixarm_ruby_unaccent
License:        NOASSERTION
Matched files:  LICENSE.md, sixarm_ruby_unaccent.gemspec
LICENSE.md:
  Content hash:  3b41f660ac82b6c90a0a8951deb1d7ad7b1dd90c
  License:       NOASSERTION
sixarm_ruby_unaccent.gemspec:
  Confidence:  90.00%
  Matcher:     Licensee::Matchers::Gemspec
  License:     NOASSERTION

$ irb
001 > require 'licensee'
 => true 
002 > license = Licensee.license 'https://github.com/SixArm/sixarm_ruby_unaccent'
 => #<Licensee::License key=other> 
003 > license.key
 => "other" 
```

**Comment by jonabc** [comment]
@sergey-alekseev hmm ok thank you.  From that data, I don't think there's anything licensed can do - can you route that question to https://github.com/licensee/licensee?
