### ISSUE TITLE
Cache all available license files

### ISSUE THREAD

**Issue by jonabc** [github/licensed#22]
First mentioned in https://github.com/github/licensed/pull/21#issuecomment-378682909.

When `licensee` finds multiple license files in a project, it doesn't attempt to determine which is the "valid" license content.  As a result the `Project#license_file` method returns nil if more than one license file is found. 

This makes sense for `licensee` but for `licensed`'s purposes, it may be useful to display all license file text.

Some considerations if all license files are written to the cached file
1. Are there any legal consequences to displaying multiple licenses if they are conflicting or it's unclear which one is valid?
1. There may be a mismatch between license content shown and the `license` metadata value
1. How to distinguish where the license content came from
   - Is this even needed?  We don't label where `Dependency#notices` files come from in the cached file

/cc @mlinksva @benbalter

**Comment by mlinksva** [comment]
1. never hurts to cache more of what the project documents about itself regarding licenses and related notices
2. in the case of multiple licenses found, that'll always be `other`, right?
3. not a requirement, but might be nice to include what file(s) licenses/notices are sourced from in the metadata

Licensee does make all this info available.

**Comment by jonabc** [comment]
> in the case of multiple licenses found, that'll always be other, right?

Not necessarily - if the project specifies a license in its package metadata (e.g. gemspec for a rubygems project), or if it's parseable from a readme then those will take precedence over `other`

**Comment by mlinksva** [comment]
Ah, right. It's still safer to include other license texts found, which could be eg for third party material the project includes and for which license notices should still be reproduced for. Of course the license text for the license identified by the project would be best output first in the cached document.

**Comment by benbalter** [comment]
> When `licensee` finds multiple license files in a project, it doesn't attempt to determine which is the "valid" license content. As a result the `Project#license_file` method returns nil if more than one license file is found.

*Technically* that behavior was implemented to preserve backward compatibility. If you call `#license_files` or `#licenses` (plural), it should give you everything it knows (but it's still up to Licensed or a human how to evaluate conflicting license information).
