### ISSUE TITLE
Cache first-level/direct dependencies only (bundler source)

### ISSUE THREAD

**Issue by pjmartorell** [github/licensed#227]
Hi! is there any option when running `licensed cache` with bundler source to only cache the licenses of the first-level/direct dependencies? I'm not interested in dependencies of the dependencies. Is it possible?

**Comment by jonabc** [comment]
@pjmartorell that isn't an option in licensed, because for generally for OSS compliance you need to list all dependencies used by a project, not just the ones directly referenced.

I'm really interested to hearing your use case - why are you only interested in direct dependencies?

**Comment by pjmartorell** [comment]
But if someone releases a gem with, in example, a MIT license which internally uses a dependency with GPL, who is the final responsible for not complying with the license? the author of the gem, the user of the gem, or both?

**Comment by jonabc** [comment]
@mlinksva :wave: do you have any guidance on ☝️?

**Comment by mlinksva** [comment]
It depends on a lot of things. If you care about licenses at all I'm not sure I see the use case for only caring about direct dependency licenses.

**Comment by pjmartorell** [comment]
In my opinion, having access to the dependencies of the dependencies is a particularity of open-source projects, I don't need to know the internals of a gem nor which dependencies it uses internally, it could even be a binary and I wouldn't even know which dependencies is the gem using. For these reasons, I think is the responsibility of the author of a gem to provide the correct license.

**Comment by mlinksva** [comment]
If you're distributing a binary you're relying on licenses from contributors to everything included in the binary, whether direct or indirect dependencies. It's up to you to know what you're shipping and comply with relevant licenses. Closing this out as I still really am not seeing the use case for ignoring transitive dependencies.
