### ISSUE TITLE
Speed up yarn source

### ISSUE THREAD

**Issue by sergey-alekseev** [github/licensed#235]
At the moment as mentioned in https://github.com/github/licensed/pull/233#issuecomment-570061513 both `licensed status` and `licensed cache` are really slow. As @jonabc explained in https://github.com/github/licensed/pull/233#issuecomment-570062085 that's because of "the extra shell execution of yarn info on each yarn dependency". May be we can skip `yarn info` calls for `licensed status` and for already cached dependencies during `licensed cache` to significantly speed up running those commands.

**Comment by sergey-alekseev** [comment]
In https://github.com/github/licensed/pull/233#issuecomment-570062085 @jonabc mentioned:  
>The extra call is used to grab the description and homepage. The description isn't as important, but giving proper attribution for the homepage might be? Not sure TBH

I quickly looked which commands Yarn offers. We could grab homepages e.g. from `yarn licenses list` – using [`VendorUrl`](https://github.com/yarnpkg/yarn/blob/v1.21.1/src/cli/commands/licenses.js#L57) or [`URL`](https://github.com/yarnpkg/yarn/blob/v1.21.1/src/cli/commands/licenses.js#L56).

**Comment by jonabc** [comment]
❤️ That's great I didn't know that the `yarn licenses` would give the url as well!  That command gives all the needed information to replace both `yarn list` and `yarn info` 👍

I can put together a PR for this pretty quickly, or happy to review one if you want to open

**Comment by sergey-alekseev** [comment]
@jonabc for efficiency I'd leave these changes for you 😃 Will test and provide feedback on a PR.

**Comment by sergey-alekseev** [comment]
BTW is there anything like https://twitter.com/hashtag/myfirstmrmerged?lang=en from GitLab? They sent me recently a mug and I wonder now if I can get something from GitHub 😄
