### ISSUE TITLE
Mix source failing - mix.lock format doesn't match expected regex evaluation

### ISSUE THREAD

**Issue by jonabc** [github/licensed#241]
ref https://github.com/github/licensed/pull/240/checks?check_run_id=451451878

It looks like where currently the mix source expects a value like `hexpm` to be the [last entry for each dependency](https://github.com/github/licensed/blob/fc4661eb2950882199d1a5e1c3a603f025b9d71e/lib/licensed/sources/mix.rb#L91-L98), there is a new last value of the hash reference that the dependency is pinned at.

For example, after running `script/source-setup/mix -f` I have an entry for mime like
```
"mime": {:hex, :mime, "1.3.1", "30ce04ab3175b6ad0bdce0035cba77bba68b813d523d1aac73d9781b4d193cf8", [:mix], [], "hexpm", "6cbe761d6a0ca5a31a0931bf4c63204bceb64538e664a8ecf784a9a6f3b875f1"},
```

:wave: @bruce as you originally wrote this source enumerator and presumably have more mix and elixir experience, are you familiar with any changes to the `mix.lock` format, and potentially how to fix this so it works for newer versions of mix/elixir as well as the versions it was written to support?

**Comment by bruce** [comment]
@jonabc I’ll look at it this evening. Thanks for letting me know.
