### ISSUE TITLE
Yarn source fails if dependency was installed in a devDependency location

### ISSUE THREAD

**Issue by gareth** [github/licensed#243]
I'm not *entirely* sure what's going on here, so I'll describe what I've seen and what I'm guessing is happening.

The `yarn` source isn't always able to find its dependency locations. It makes an assumption that dependencies are always found inside their parent dependency:

https://github.com/github/licensed/blob/ef02cc78cd4b24b31d18596be0530b086b9879c0/lib/licensed/sources/yarn.rb#L65

However, this doesn't seem to be true. If Yarn has already installed an identical version of a dependency, it seems to put later copies directly inside the top-level `node_modules` folder (see the end of my reproduction steps below). So the correctly nested node_module only seems to exist inside one dependency.

If the same version of a nested dependency is required by both a production dependency and a development dependency, it's possible that the node_module is installed only inside the development dependency.

This causes problems because the `yarn` source adds `--production` to its list command, which means it's impossible for it to find a nested dependency that doesn't exist inside the installed production dependencies.

Note this problem isn't solved by setting the `production_only` option to false: I **do** only want to generate license conflicts for _production dependencies_, it's just that yarn may only have stored that license information inside a _development dependency's_ `node_modules`.

It was tricky coming up with a minimal test case for this, but this seems to demonstrate it. It also shows that the `npm` source doesn't seem to have this problem (it's correctly able to find the right license info):

```
$ yarn --version
1.22.0
$ licensed --version
2.8.0
$ mkdir licensed-test; cd licensed-test
$ printf "sources:\n  npm: true\n  yarn: true" > .licensed.yml
$ yarn add -s --no-progress babel-loader@8.0.6
warning " > babel-loader@8.0.6" has unmet peer dependency "@babel/core@^7.0.0".
warning " > babel-loader@8.0.6" has unmet peer dependency "webpack@>=2".
$ yarn add -D -s --no-progress vue-jest@3.0.5
warning package.json: No license field
warning No license field
warning vue-jest > babel-plugin-transform-es2015-modules-commonjs > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning " > babel-loader@8.0.6" has unmet peer dependency "@babel/core@^7.0.0".
warning " > babel-loader@8.0.6" has unmet peer dependency "webpack@>=2".
warning " > vue-jest@3.0.5" has unmet peer dependency "babel-core@^6.25.0 || ^7.0.0-0".
warning " > vue-jest@3.0.5" has unmet peer dependency "vue@^2.x".
warning " > vue-jest@3.0.5" has unmet peer dependency "vue-template-compiler@^2.x".
warning No license field
$ licensed cache
Caching dependency records for licensed-test
  npm
    Caching babel-loader (8.0.6)
    Caching big.js (5.2.2)
    Caching commondir (1.0.1)
    Caching emojis-list (3.0.0)
    Caching find-cache-dir (2.1.0)
    Caching find-up (3.0.0)
    Caching json5 (1.0.1)
    Caching loader-utils (1.4.0)
    Caching locate-path (3.0.0)
    Caching make-dir (2.1.0)
    Caching minimist-0.0.8 (0.0.8)
    Caching minimist-1.2.0 (1.2.0)
    Caching mkdirp (0.5.1)
    Caching p-limit (2.2.2)
    Caching p-locate (3.0.0)
    Caching p-try (2.2.0)
    Caching path-exists (3.0.0)
    Caching pify (4.0.1)
    Caching pkg-dir (3.0.0)
    Caching semver (5.7.1)
  * 20 npm dependencies
  yarn
    Caching babel-loader (8.0.6)
    Caching big.js (5.2.2)
    Caching commondir (1.0.1)
    Caching emojis-list (3.0.0)
    Caching find-cache-dir (2.1.0)
    Caching find-up (3.0.0)
    Caching json5 (1.0.1)
    Caching loader-utils (1.4.0)
    Caching locate-path (3.0.0)
    Caching make-dir (2.1.0)
    Caching minimist-0.0.8 (0.0.8)
    Caching minimist-1.2.0 (1.2.0)
    Caching mkdirp (0.5.1)
    Caching p-limit (2.2.2)
    Caching p-locate (3.0.0)
    Caching p-try (2.2.0)
    Caching path-exists (3.0.0)
    Caching pify (4.0.1)
    Caching pkg-dir (3.0.0)
    Caching semver (5.7.1)

  * Warnings:
    * licensed-test.yarn.minimist-1.2.0
    cached: true
      - expected dependency path /Users/gareth/licensed-test/node_modules/json5/node_modules/minimist does not exist

  * 20 yarn dependencies
$ find node_modules -name minimist
node_modules/loader-utils/node_modules/minimist
node_modules/minimist
$
```

**Comment by jonabc** [comment]
Wow great find @gareth 🙇 .  If you have any ideas on how to fix it I'd gladly review a PR.  Otherwise I don't have much free time at the moment and a fix may take a little while.

**Comment by gareth** [comment]
I'll try and find some time to look into it, but in the meantime it would be good to at least have confirmation that the issue is reproducible (i.e. isn't something weird with my `yarn` setup).

It would also be good to hear whether you agree that this is the problem (that the install location assumption might be wrong), even if you don't immediately know how to fix it.

**Comment by jonabc** [comment]
> but in the meantime it would be good to at least have confirmation that the issue is reproducible (i.e. isn't something weird with my yarn setup).
> It would also be good to hear whether you agree that this is the problem (that the install location assumption might be wrong), even if you don't immediately know how to fix it.

TBH I'm not super familiar with yarn and couldn't answer these questions without digging in a bit.  What you've described and reproduced sounds very plausible though.

One thing that would be interesting to try from your reproduction case - if you prune yarn's installed packages to only include production dependencies (maybe `yarn install --production`?), does yarn know to fix the problem?  That doesn't fix the issue for local development environments but might at least make things workable for status checks in CI.

**Comment by gareth** [comment]
Actually, it turns out I see *more* errors if I remove `node_modules` and use `yarn install --production` to re-add them.

That was actually a surprise, I thought it would work. It will take more looking at to be sure what's happening.

**Comment by gareth** [comment]
Ok, I understand the reason this happens now, and the TL;DR is: While `yarn list` does correctly list the _logical_ dependencies of an application, there's no guarantee that the nesting relates to the physical location of the dependencies on disk.

I still don't have a suggested solution.

Let's explain by example - now I've found a simpler minimal test case than before. In this summary I'm going to be using this inefficient and probably-not-bulletproof one-liner to list actual package install locations:
```
$ jq -r '(input_filename|sub("/package.json";"")) + "#" + .version' **/node_modules/*/package.json | sort | sed 's:node_modules/:…/:g' | sed 's/#/@/'
```
Let's start with two modules, each of which depend on a different version of `through`:
```
$ yarn add split@1.0.1 ls-stream@1.0.0
```
That leads to a `yarn list` that matches the installed packages:
![image](https://user-images.githubusercontent.com/4975/75872079-7a6c8080-5e05-11ea-9b16-f0e1a1739a75.png)
```
…/ls-stream@1.0.0
…/ls-stream/…/through@2.2.7
…/split@1.0.1
…/through@2.3.8
```
Yarn arranges dependencies to suit Node's module loader algorithm - dependencies can look in their own `node_modules` folder for nested dependencies, and iterate up the tree if they aren't present there. (documented at least [in Webpack's documentation](https://webpack.js.org/configuration/resolve/#resolvemodules))

So in this case `split` would fail to find `through` in its own directory but would find it in the top-level directory. Because of this algorithm, yarn could have chosen either `through` version to store at the top level so long as the other version was correctly nested. I believe it chooses the newest version to store at the top level (it may also try and minimise the number of copies of a library, I'm not sure).

So far, so normal.

Now let's add the older version of `through` as a development dependency. Yarn rearranges the tree to put our dependency version at the top level and moves the other version to be nested (these file locations are the same when `yarn install --production` is used):

```
$ yarn add -D through@2.2.7
[…]
$ package_tree
…/ls-stream@1.0.0
…/split@1.0.1
…/split/…/through@2.3.8
…/through@2.2.7
```

However `yarn list` and `yarn list --production` now behave differently, despite being backed by the same filesystem (the same is true for the JSON output that `licensed` uses):

![image](https://user-images.githubusercontent.com/4975/75873360-a983f180-5e07-11ea-9b63-e644ba139ca4.png)

As you can see, `yarn list --production` represents the dependency nesting completely ignoring the development dependencies, even though that's not where the files have now been stored.

This means two things are now wrong for `licensed`:

* It can't find `through@2.2.7` in the location it's trying to look: `node_modules/ls-stream/node_modules/through` and throws a warning
* It looks for `through@2.3.8` in `node_modules/through` but **that's where 2.2.7 is stored(!)** -  no error is thrown but **it's processed the wrong version**.

### Conclusions

I think it's right for `licensed` to not process development libraries in most cases, and at least by default. But it's clearly not possible to rely on the structure of `yarn list --production` to find out where applicable license files are.

**Comment by jonabc** [comment]
@gareth ❤️ great analysis, thank you for the writeup!  Gonna have a think on that one but I still have little time at the moment to put towards an actual fix 😞 .

If I think of anything I'll add it here, if you think of anything please do feel free to either document it here or open a PR 🙇

**Comment by gareth** [comment]
As I understand it, anyone using `yarn` to install their dependencies can still use the `npm` source in `licensed` because the two sets of install locations are compatible. I guess there may be yarn config options that stop that being viable, but it's what we're using as a replacement in our organisation.
