### ISSUE TITLE
Allow detection of licenses changed after being `reviewed`

### ISSUE THREAD

**Issue by gareth** [github/licensed#244]
This is an open-ended question/feature request because a) I realise this isn't a trivial change and b) I can't even think about how you'd go about implementing it.

At the moment, I can review any dependency that `licensed` doesn't identify as one of my "allowed" licenses, and whitelist it by adding it to the `reviewed:` key. Most commonly this helps where `licensed` tags a dependency as "other", but I'm able to determine that it's just been mislabeled because `licensee` has detected some irrelevant additional text/files in the library.

However, because this dependency is now whitelisted, it's impossible to detect if that license information is later changed for a different license, that I might not allow.

One thing I think *wouldn't* work is changing the `reviewed` syntax to allow `package@version` labels and just compare whether `current_version > reviewed_version`. It would be tedious to force re-review every version bump when nearly all version bumps don't change license information<sup>[citation needed]</sup>.

My first impression is that the "correct" solution for this would require persisting the license cache and actually detecting changes to the license texts themselves - which definitely doesn't sound simple.

I realise that `licensed` isn't supposed to be a strict compliance tool and so I understand this might be `WONTFIX`, but I wanted to open the discussion. If anyone has ideas for an approach then I might be able to look at a PR.

**Comment by mlinksva** [comment]
I agree this would be valuable, and on the correct solution in concept: re-review when license info has changed.

**Comment by jonabc** [comment]
> My first impression is that the "correct" solution for this would require persisting the license cache and actually detecting changes to the license texts themselves - which definitely doesn't sound simple.

Unless I'm misunderstanding, licensed already does this for a different purpose 😄 

When caching licenses, we check the current license text vs the cached license text to determine whether to keep the pre-existing license classification on dependency version changes.
https://github.com/github/licensed/blob/ef02cc78cd4b24b31d18596be0530b086b9879c0/lib/licensed/commands/cache.rb#L49
https://github.com/github/licensed/blob/ef02cc78cd4b24b31d18596be0530b086b9879c0/lib/licensed/dependency_record.rb#L87-L90

Generally this could be done, I'm just unclear on the specific scenario and what should happen when we detect that the license text has changed.

Off the top of my head the solution that would seem to work is to remove the dependency from the `reviewed` list, but given the disconnect between when `licensed cache` is run from `licensed status`, that could get really confusing for users.

**Comment by gareth** [comment]
> Unless I'm misunderstanding, licensed already does this for a different purpose

Oh great!

Well, in that case, I don't think the algorithm is too difficult:

1. Require/allow people to specify which version they have reviewed
2. Track the *earliest* version that a particular license text was seen. 
3. If at any point, license version is greater than reviewed version (via [semver](https://semver.org/) comparison?), throw an error

So, if I review the current version of a gem which we then cache:
```
reviewed:
  bundler:
    - dodgy_gem@4.2.5
```

```
---
name: dodgy_gem
version: 4.2.5
license_version: 4.2.5
sources: […]
```

The gem is later updated **without** license change:
```
---
name: dodgy_gem
version: 4.3.2
license_version: 4.2.5
sources: […]
```
(no error on status check because `license_version <= reviewed_version`)

The gem is later updated **with** license change:
```
---
name: dodgy_gem
version: 4.4.1
license_version: 4.4.1
sources: […]
```
(error on status check because `license_version > reviewed_version`)

Is there any reason this couldn't work in principle?

**Comment by jonabc** [comment]
@gareth a few concerns there:
1. it's not clear how to handle existing users that don't include a version number in the reviewed data
   - requiring a version number in the reviewed list would break back-compat and require a major version update and migration which might be too much to ask
   - making it optional means most users won't get the benefit
2. some of the sources (pre-modules go, manifest) use non-semver based versions which then makes this very hard to compare

Since license text comparisons isn't that big of a deal, what do you think instead about setting a flag when caching metadata, when a dependency is set as reviewed and license text(s) have changed
```
---
name: ...
version: ...
needs_review: true
...
```

Then in `licensed status` it's easy enough to check that metadata and post an error with instructions to re-review the license text and remove the `needs_review` flag.

/cc @mlinksva for thoughts on explicit version vs flagging in metadata in case you see any additional concerns with either approach

**Comment by mlinksva** [comment]
I don't think anything is gained by setting a reviewed version. I love setting a flag when dependency is reviewed and license text(s) have changed!
