### ISSUE TITLE
Unmet peer dependencies trigger failure; even when unnecessary

### ISSUE THREAD

**Issue by jasonkarns** [github/licensed#264]
Npm does not install peerDependencies of direct dependencies; it emits warnings if the expected peer dependency is not installed.

Npm itself does not provide a mechanism to define a peer dependency as optional.  As such, it seems common (anecdotally) in cases where a peer dep is not actually used, for projects to simply ignore the unmet peerdep warning. However, licensed considers this a hard error:

```
* github.npm.@react-native-community/async-storage
  filename: [/snip]/vendor/licenses/npm/@react-native-community/async-storage.dep.yml
    - cached dependency record not found
```

Considering that npm _itself_ does not consider an unmet peer dependency to be an error, it seems that licensed should also not consider this an error.

**Comment by jonabc** [comment]
@jasonkarns just to make sure I understand the scenario - the peer dependency is optional and _not_ included in any shipped product, but licensed doesn't understand this case and still thinks the dependency should be logged?

**Comment by jasonkarns** [comment]
@jonabc correct.

I haven't dug into licensed to see how it interrogates npm for the list of deps; but as far as npm is concerned, the dep is not in the tree:

```sh
$ npm ls --json @react-native-community/async-storage
{}
```

**Comment by jonabc** [comment]
@jasonkarns :wave: I think what you're proposing, to treat missing peers as optional, makes sense.  The user has decided not to install the package, and if it won't ship with the product it shouldn't raise an error.  If the package is installed, it should continue to be reported 👍
