### ISSUE TITLE
could not find X in any sources

### ISSUE THREAD

**Issue by klautcomputing** [github/licensed#271]
Running `licensed cache` locally on my project it errors with:

```
  * Errors:
    * backend.bundler.mysql2
      - could not find mysql2 (>= 0) in any sources
```

running it in a github action there are many more that it cannot find:

```
  * Warnings:
    * backend.bundler.minitest
    cached: true
      - expected dependency path /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/minitest-5.10.3 does not exist


  * Errors:
    * backend.bundler.google-protobuf
      - could not find google-protobuf (>= 0) in any sources

    * backend.bundler.mocha
      - could not find mocha (>= 0) in any sources

    * backend.bundler.mysql2
      - could not find mysql2 (>= 0) in any sources

    * backend.bundler.rbnacl
      - could not find rbnacl (>= 0) in any sources
```
(my action might be older)

Any idea what's wrong here? Almost forgot I am running `licensed version 2.10.0`

**Comment by jonabc** [comment]
@klautcomputing to check the basics
- did you run `bundle install` in all scenarios before running licensed?
- do you have any custom configuration on bundler or rubygems relating to where gems are stored?

**Comment by klautcomputing** [comment]
That was totally it 👍 

I think more documentation around the project would have helped me figure this out on my own, now there's an issue for everyone who's running into the same issue.
