### ISSUE TITLE
Aggregated output reports from licensed

### ISSUE THREAD

**Issue by jonabc** [github/licensed#278]
@gq-dot :wave: thanks for getting in touch, lets use this issue to discuss what you're looking for 👍 

Can you describe the scenario you want to address, and the result you'd like to see?  I wasn't quite sure what you were asking for with 

> I’m wondering if you know of any good ways to turn the individual xml outputs in to an aggregated report?

**Comment by GregoriousQ** [comment]
Appreciated.

I have an electron app that uses many npm libraries.
I'm tasked with generating a report going over what OSS licenses are in use.

I'm wondering if there is a recommended way to the .xml files that licensed/licensee generates and turning them in to an aggregated report of all licenses used by the project.

**Comment by jonabc** [comment]
@GregoriousQ it's not necessarily a "report", but I recently opened a PR from some other requests for licensed to create a [NOTICE file](https://github.com/github/licensed/pull/277).  Would that solve what you're looking for?  Or are you looking for a different type of aggregation?

**Comment by gq-dot** [comment]
👌I think that would work well for what I’m trying to accomplish. I’ll check the PR out and give it a whirl. 🙏

**Comment by jonabc** [comment]
@gq-dot @GregoriousQ :wave: have you had a chance to check out the `licensed notices` command, and does it accomplish the goal of this request?

**Comment by gq-dot** [comment]
Yes. the licensed notices command accomplishes the goal of the request 100%
Thank you!

![](https://media0.giphy.com/media/nj0wszRab0Mxi/giphy.gif)
