### ISSUE TITLE
Add CLI arg to override which sources to use in a particular scenario

### ISSUE THREAD

**Issue by jonabc** [github/licensed#286]
This could be useful as a performance bump when running licensed manually when:
1. a project references dependencies from multiple source types (bundler, npm, etc)
2. automation ties a new install to running licensed, e.g. `bundle install` is hooked to call `licensed cache`

In the above scenario there's no reason to recache or reevaluate licenses for anything but bundler, and a CLI option seems like a minimal lift to help out here.

The only thing this needs to really be aware of is that existing licenses will get deleted for sources that are not evaluated.  Any solution needs to bypass cached data from other sources 👍

**Comment by sergey-alekseev** [comment]
Great idea! I released https://rubygems.org/gems/bundler-licensed/versions/0.2.0 which uses this feature.
