### ISSUE TITLE
Why does `status` take so long?

### ISSUE THREAD

**Issue by cobbr2** [github/licensed#296]
I've got a Rails / Yarn application I'm analyzing with about 3000 dependencies.  I can understand `licensed cache` taking  a long time to grab those licenses (> 1 hour), but `licensed status` takes about 30 *minutes*.  It would seem to me that this is just looking at the 'licensed:' field from my 3000 already-cached YAML files and checking against my approval list, which should take seconds, even in Ruby.  What's up?  Is it trying to refresh the cache? I'm using the gem in this case, rather than the executable; I may try the executable.

(Oh, and of course since this is a first analysis of this repo with `licensed`, of course >800 of them are not on approved licenses yet, if that matters for the explanation.)

**Comment by jonabc** [comment]
@cobbr2 there are more verifications that take place than just checking `licensed:` fields in the yaml files which causes the longer runtime you're experiencing.  Licensed still must enumerate every dependency in your project to make sure they all have cached data.  

For bundler, that means using bundlers programmatic API to parse your Gemfile and Gemfile.lock and produce the full list of dependencies used. In certain cases bundler dependencies may need additional invocations of the `gem` cli. 
For yarn, that means calling into the `yarn` CLI to provide the list of dependencies.

The `status` command doesn't make any additional calls to get information on dependencies, find their location on disk, search for license files, match license file contents against known OSS licenses or cache data to disk.  TBH it doesn't really do much except call into package managers to gather and return basic information about what dependencies are included.

With large projects the cost for package managers to enumerate dependencies is usually pretty high.  If there's a more performant way to do any of this that doesn't compromise functionality I'd gladly welcome a PR!

I'm going to close this for now as I'm not sure what else can be done here, but please reopen if you have additional concerns.

**Comment by cobbr2** [comment]
I'm obviously missing something about bundler and its API here; if 'bundle install' returns in 5 seconds, it must have run that tree down in less than five seconds.  In our CI/CD world (and in the test environment in my workstation), we have already bundled and yarn'ed the app before running `licensed status`, so everything *should* already be local. Yet: 30 minutes.  Does `licensed` rebundle into a pristine sandbox when it does this analysis? If so, why?

**Comment by jonabc** [comment]
> I'm obviously missing something about bundler and its API here

@cobbr2 you and me both maybe.  If the bundler CLI itself is running that quickly then either 

1. there are potentially other, faster, bundler APIs which licensed could use.
   - what bundler version are you on?  I generally try to avoid using APIs that target specific versions of bundler to reduce code sharding and maintenance costs, but if thats the only way to reduce cost here then so be it.
2. With that many dependencies `Set` comparison costs are an issue
   - I'm not sure what `Set` uses internally but if it involves any sort of iteration then we can reduce cost significantly here with a hash

How long does it take to run `npm list --long --json --production`?  Let's also rule out that npm is taking a long time to iterate through

One last question - can you set up a basic repo project with a Gemfile, package.json, and their respective lockfiles?  If you can share that with me when I have some more time I can dig in and see whether the cost is with licensed or with one or more of the package managers.

**Comment by jonabc** [comment]
@cobbr2 I'm unable to recreate your experience.  I've set up a repro environment with 343 bundler dependencies and >6000 yarn dependencies.

Both caching and checking status on that many bundler dependencies each take in the 1-2 second range

Caching yarn dependencies takes a minute or two, with roughly equal time spent between `yarn` commands and licensed cache.  Checking the status of cached yarn data is in the ~30 seconds range.

It's possible that at some point between 343 gems and the number you're using that there is some drastic decrease in performance but I'm not sure how/why/where.  Without a repro project, knowing more about the dependencies you're using, or knowing more details about the environments you're running licensed in it's hard to dig in further.

What versions of licensed, ruby, bundler, node/npm and yarn are you using?

**Comment by cobbr2** [comment]
I'm hoping to get back to this later today. Thank you for your attention!
