### ISSUE TITLE
Add support for Gradle multi-module projects.

### ISSUE THREAD

**Issue by CristianGM** [github/licensed#301]
The approach to inject the plugin dependency-license-report plugin used [here](https://github.com/github/licensed/blob/master/lib/licensed/sources/gradle.rb#L147) is making a modified copy of the build.gradle and running it with `-b`, it means Gradle will ignore the settings.gradle and ignore all the subprojects (modules).

I asked on Gradle Slack and they told me to use an init script instead so it works properly, that will also fix the issue that we are only considering `build.gradle` and not the "new" `build.gradle.kts` which would change the syntax slightly.

Alternatively it would be possible to copy the settings.gradle to another file adding to it `rootProject.buildFileName = "license-....gradle"`´ and using it adding to the cli `-c licensed-settings.gradle`, but then we still need to add support for `.gradle.kts` files

**Comment by jonabc** [comment]
@CristianGM I don't have deep knowledge of Gradle, but am happy with any changes that maintain backwards compatibility while solving the problems you mention. Would you be able to open a PR?

**Comment by jonabc** [comment]
This was resolved with https://github.com/github/licensed/pull/583, which will be part of the major version 4.0 release
