### ISSUE TITLE
npm source does not use license value from package.json

### ISSUE THREAD

**Issue by rreinurm** [github/licensed#325]
Some npm licenses are not detected because licence in package.json don't match with content from LICENSE for example https://github.com/nodejs/string_decoder

`licensed status` produces
```
* app.npm.string_decoder
  filename: /app/cache/npm/string_decoder.dep.yml
    - license needs review: other
```
Same time `licensee detect` produces:
```
License:        NOASSERTION
Matched files:  LICENSE, package.json
LICENSE:
  Content hash:  c0f755e090e653b4bd58fee2761e09ed39358e4c
  License:       NOASSERTION
  Closest non-matching licenses:
    NCSA similarity:     57.14%
    MIT similarity:      55.76%
    UPL-1.0 similarity:  52.90%
package.json:
  Confidence:  90.00%
  Matcher:     Licensee::Matchers::NpmBower
  License:     MIT
```

Would it make sense to use value from package.json in case of value "NOASSERTION" from License file?

**Comment by jonabc** [comment]
@rreinurm this is likely a better question to pose in https://github.com/licensee/licensee.  From the `licensee detect` output, licensee is finding both the package.json content and the LICENSE file content.  This project attempts to stay away from making any assertions about what licenses are found, or which found license is valid.

I'm going to close this, but please feel free to reopen if you have a strong objection to moving this conversation to licensee.
