### ISSUE TITLE
Having trouble with setting up licensed "missing license text"

### ISSUE THREAD

**Issue by lowlighter** [github/licensed#333]
Hello!

I followed the docs but I'm still having some trouble figuring how to make it work 😕

Here's my `.licensed.yml` config file:
```yaml
source_path: .
cache_path: .licensed
```

And below the commands I ran (basically trying to run **licensed** over a NodeJS repository):
```shell
git clone https://github.com/user/test # example 
cd test
npm ci
vi .licensed.yml 
licensed cache
licensed status
```

`licensed cache` seems to works but I'm getting the following errors on `licensed status`:
```diff
- missing license text
- license needs review: none

209 dependencies, 418 errors found # i.e. all dependencies
```

#324 seemed to have a similar error (although from what I understood it was for the GitHub action version, I'm trying to run the executable), so I added `allowed: [none]` and it make all `license needs review: none` errors disappears, but I'm still encountering *missing license text*.

Seems licenses aren't correclty detected as they exists:
```
ls node_modules/axios
CHANGELOG.md dist index.d.ts index.js lib LICENSE package.json README.md UPGRADE_GUIDE.md
```
But cached files are empty (all of them): 
```yaml
---
name: axios
version: 0.21.1
type: npm
summary:
homepage:
license: none
licenses: []
notices: []
```

What I am missing?

___

Also, is there any example output? I'm not sure yet that **licensed** is the tool that I need for what I want to achieve, I may have misunderstood its utility.

Thanks a lot!

**Comment by jonabc** [comment]
@lowlighter it looks like licensed is unable to find any of the dependencies on disk even after you've run npm ci.  In that same environment after running `npm ci` can you run `npm list --json --long --production` and check:
1. does the command succeed?  if there are errors, what are the errors?
2. do returned packages' `path` property point to a valid location on disk that contains the the installed dependency?

> Also, is there any example output? I'm not sure yet that licensed is the tool that I need for what I want to achieve, I may have misunderstood its utility.

The output that you've seen is the 90% case of what licensed does, with the exception that the files which are currently empty should not be empty 😅 .  If you can share what you're trying to achieve I may be able to tell you whether licensed is a good fit or not.  Please let me know if you have any other questions as well 🙇

**Comment by lowlighter** [comment]
Running `npm list --json --long --production` was displaying some warnings before JSON output (npm/NodeJS from apt repo were outdated on my vm). Installing them from nodesource to be up-to-date solved the problem 👍

I assume these warnings were piped to **licensed** making the JSON unparsable. Not sure but maybe stderr is redirected to stdout. 

Anyway it's working fine now, thanks for your help 🙂 !

___

As for second question, I'm currently working on a [tool](https://github.com/lowlighter/metrics) which create SVG images and I was planning to make a license plugin which looks a bit like [FOSSA's badges](https://app.fossa.io/api/projects/git%2Bgithub.com%2Fbevry%2Ftaskgroup.svg?type=large). 

So I'm looking for a tool which is able to list dependencies of a project along with their associated licenses, like the following:

<details>
<summary>Desired output</summary>

```json
{
  "..npm.@actions/core": "mit",
  "..npm.@actions/github": "mit",
  "..npm.@octokit/graphql": "mit",
  "..npm.@octokit/rest": "mit",
  "..npm.axios": "mit",​
  "..npm.compression": "mit",​
  "..npm.ejs": "apache-2.0",​
  "..npm.express": "mit",​
  "..npm.express-rate-limit": "mit",​
  "..npm.faker": "other",​
  "..npm.image-to-base64": "mit",​
  "..npm.js-yaml": "mit",​
  "..npm.memory-cache": "bsd-2-clause",​
  "..npm.prismjs": "mit",​
  "..npm.puppeteer": "apache-2.0",​
  "..npm.simple-git": "mit",​
  "..npm.svgo": "other",​
  "..npm.vue": "mit",​
  "..npm.vue-prism-component": "mit",
}
```

</details>

I looked at both [licensee/licensee](https://github.com/licensee/licensee) and [github/licensed](https://github.com/github/licensed) but the latter seemed to suit more my needs, although it looks more like a license compliancy enforcer.

I didn't find a native way to do it with **licensed** (I may have missed it), but I'm able to generate the output above with `licensed status --format=json`, an empty `allowed` parameter and extracting license from error messages. But not sure if I'm stretching the use of this library, seems a bit hacky 😅 

As I noticed **licensed** has a lot of [supported sources](https://github.com/github/licensed#sources) and I'd like to be language agnostic, it seems a good fit. Others libraries I found are usually scoped to their project/languages.

Thanks again for your hindsight!

**Comment by jonabc** [comment]
> I assume these warnings were piped to licensed making the JSON unparsable. Not sure but maybe stderr is redirected to stdout.

stderr is kept separate from stdout, but if the warnings were included in stdout that could cause the issue.  You _should_ have seen [this error](https://github.com/github/licensed/blob/88c9c838885d1c19926b2e03ce9b5e6999ed77ec/lib/licensed/sources/npm.rb#L65-L67) somewhere in the output though if the JSON couldn't be parsed.  It's also possible that the JSON could be parsed but the data was not in the expected format.  If you're able to provide a repro scenario for the original issue that doesn't contain any sensitive or proprietary information I'd be happy to dig in a bit further.

Either way, glad you were able to get past the immediate issue.

> I looked at both licensee/licensee and github/licensed but the latter seemed to suit more my needs, although it looks more like a license compliancy enforcer.

yep, dependency tracking and compliance enforcement is the main goal here.

> I didn't find a native way to do it with licensed (I may have missed it), but I'm able to generate the output above with licensed status --format=json, an empty allowed parameter and extracting license from error messages. But not sure if I'm stretching the use of this library, seems a bit hacky 😅

This got me curious and I've got together a quick update that could give something like the above output by extending `licensed list` to support different output formats and including more information in the output.  That unfortunately has some performance implications to that command so I'd need to review and see how to make the new functionality available without degrading general usage.

The other option is to run `licensed cache` and then use some bash scripting over the created files to read the name and license yaml keys.

I'd give a word of caution though.  This project uses licensee to detect licenses and by licensee's nature of parsing license text to determine a match, there is the possibility for licensee to not determine a match for something you'd look at and say "of course this is MIT, it's obvious".  There is some manual review expected when using this tool and it may not be a perfect fit for a fully automated workflow.

**Comment by lowlighter** [comment]
I think there were actually no errors, I probably used a bad configuration at first which resulted in an empty output, and didn't noticed there were a `--force` param in `licensed cache` so licenses files probably weren't updated. Tried to reproduce with a fresh vm with **licensed** correctly configured and it worked as expected, even with outdated npm/node 👍

I've seen the disclaimer but I intend to use it more for informative purposes rather than legals ones, so it should be ok. 
I'll probably use your solution to iterate over parsed yaml which seems more reliable than parsing errors messages. 
If you ever introduce a feature to just list dependencies with their licenses, don't hesitate to @ me, I'll be happy to test it 🙂

Thanks for your help and your work!
