### ISSUE TITLE
NuGet Source should search in fallbackFolders if package is not found in packagesPath

### ISSUE THREAD

**Issue by JanMattner** [github/licensed#352]
Typically, the System/MS packages are not stored in the user's NuGet cache folder, but in the SDK's "Fallback Folder".

Part of my project.assets.json:

```
  "packageFolders": {
    "C:\\Users\\jan.mattner\\.nuget\\packages\\": {},
    "C:\\Program Files\\dotnet\\sdk\\NuGetFallbackFolder": {}
  },
  "project": {
    "version": "1.1.2289.7",
    "restore": {
      "projectUniqueName": "C:\\path\\to\\project\\myproject.csproj",
      "projectName": "MyProject",
      "projectPath": "C:\\path\\to\\project\\myproject.csproj",
      "packagesPath": "C:\\Users\\jan.mattner\\.nuget\\packages\\",
      "outputPath": "C:\\path\\to\\project\\obj\\",
      "projectStyle": "PackageReference",
      "crossTargeting": true,
      "fallbackFolders": [
        "C:\\Program Files\\dotnet\\sdk\\NuGetFallbackFolder"
      ],
```

Currently, the NuGet Source only considers:
https://github.com/github/licensed/blob/0d31c466dabaea259ccef45dd5ad823c56a29780/lib/licensed/sources/nuget.rb#L184

Then with the `licensed cache` command I get the following warning:

```
   * Warnings:
    * MyProject.nuget.Microsoft.CSharp-4.0.1
      - expected dependency path C:\Users\jan.mattner\.nuget\packages\microsoft.csharp/4.0.1 does not exist
```

But in fact, it exists at `C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.csharp\4.0.1`

So I propose that if the file is not found in the "primary" packagesPath, then it should search all the other fallbackFolders.

**Comment by jonabc** [comment]
:wave: Hi @JanMattner thanks for bringing this up!  There's a PR about this that's been open for quite awhile at https://github.com/github/licensed/pull/273, I'll take another look at that and see if I can clean that up to get it merge-able.
