### ISSUE TITLE
NuGet Source - Support better App Naming when using Glob Patterns

### ISSUE THREAD

**Issue by JanMattner** [github/licensed#355]
Currently for the NuGet Source, is is required to set the `source_path` to the object folder of a project, which is typically in `some/path/MyProject/obj` for a project with name `MyProject`. So, a Dotnet project is a single "app" (for GitHub Licensed).

If I have 100 of those, I rather use the glob pattern `some/path/*/obj`.
Problem: all apps are then named "obj" which is not useful when trying to find out which license is used in which project.
Thus in practice, the glob pattern is not useful with NuGet Source.

Suggestion: the source_path could be set to the project folder and NuGet Source internally checks for the "obj" subfolder (and if it does not exist, NuGet Source looks directly in the source_path for the project.assets.json). Then my glob would be `some/path/*` and the app name would be the project name.

Alternatively I could think of a new property just for the obj folder of an app.

Do you have any other suggestions?

**Comment by jonabc** [comment]
@JanMattner interesting, when the NuGet source was first built I recall asking a question along similar lines as the above, and being told that the common pattern was to have a single `obj` folder outside the path of individual projects. The projects' obj outputs are subfolders of `obj` in that model - `some/path/obj/*` .

I'm not sure the best way to reconcile those two types of glob patterns, maybe a new `obj_path` configuration value or similar that the NuGet source can use on top of the given source paths?  so you could have something like the following to enable your use case?

```yaml
source_path: some/path/*
nuget:
  obj_path: obj
```

**Comment by JanMattner** [comment]
That's interesting, I was not aware of that pattern and to be honest - I have never seen it in any project. At least the default behavior is one obj folder per project (csproj) and I think many Apps/Projects use it in such a way. So it would be great for GitHub Licensed to support this default pattern, so applying it is as easy as possible.

Great suggestion, with "obj_path" defaulting to an empty string, we could keep backwards compatibility to the current behavior.

**Comment by JanMattner** [comment]
Any news on this?

**Comment by jonabc** [comment]
@JanMattner sorry no, at least not from my perspective.  I've been busy with other tasks and don't have much bandwidth right now to look at this.  I could try to fit this into one of the next few weekends, but can't make any promises.  If you have a pressing need and are familiar with Ruby I'd happily review/advise on a PR though

**Comment by JanMattner** [comment]
@jonabc Thanks for the PR! Unfortunately I have never done anything with Ruby :( 
But I can try to build and test it in a real world example.
