### ISSUE TITLE
Error when specifying a bundler gem from a git repo

### ISSUE THREAD

**Issue by clinejj** [github/licensed#359]
### Describe the bug

When using a git repo for a bundler gem, licensee reports the following error and any licensed command fails:
```
Search root must be the project path directory or its ancestor
from /Users/john/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/licensed-3.0.0/lib/licensed/dependency.rb:40:in `initialize'
        from /Users/john/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/licensed-3.0.0/lib/licensed/sources/bundler.rb:17:in `initialize'
        from /Users/john/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/licensed-3.0.0/lib/licensed/sources/bundler.rb:60:in `new'
        from /Users/john/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/licensed-3.0.0/lib/licensed/sources/bundler.rb:60:in `block (2 levels) in enumerate_dependencies'
```

My gemfile specifies:
```
gem 'active_admin_import', '>= 4.2.1.ruby3', git: 'https://github.com/Shelf-Life/active_admin_import'
```
At that line, it seems licensed is expecting a different folder than what the gem is installed to:
```
Search root must be the project path directory or its ancestor: /Users/john/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/active_admin_import-4.2.1.ruby3 and /Users/john/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/active_admin_import-3997e99f222e
```
are defined for root and path at this line: https://github.com/licensee/licensee/blob/master/lib/licensee/projects/fs_project.rb#L23

I had filed with licensee here and was suggested this was an issue with licensed: https://github.com/licensee/licensee/issues/492

This appears to be due to a mismatch between what licensed passes to licensee as the search root for these types of dependencies.

### Steps to reproduce the behavior

1. Add the above gem to a gemfile for a Ruby project
2. Run `bundle install`
3. Run `gem install licensed`
4. Run `licensed cache`

### Expected behavior

`licensed` should run as expected with no errors.

**Comment by jonabc** [comment]
Thanks for the report.  I took a look into the cause and have a small change incoming that should fix this.
