### ISSUE TITLE
Filtering out local Go packages is case-sensitive and can cause local packages to not be excluded

### ISSUE THREAD

**Issue by andreas-hakansson-ingka** [github/licensed#369]
Hi

We noticed that if we have code in a directory such as `~/code/` and we go into that directory using another casing such as `~/codE/` and run `licensed status`, it will fail.

The reason is that `git rev-parse --show-toplevel` as it's used in https://github.com/github/licensed/blob/4fdf7353c5750fec847a4f23aaf3b48403e83362/lib/licensed/git.rb#L12-L17 returns a canonicalized path whereas `package["Dir"]` does not. That causes the comparison in `local_package?` https://github.com/github/licensed/blob/4fdf7353c5750fec847a4f23aaf3b48403e83362/lib/licensed/sources/go.rb#L99-L103 to fail and it ends up including local packages as well.

The matching should probably be made case-insensitive https://github.com/github/licensed/blob/4fdf7353c5750fec847a4f23aaf3b48403e83362/lib/licensed/sources/go.rb#L101

This was a bit of a head-scratcher to figure out why it was failing on 1 out of 4 dev machines 😄

**Comment by jonabc** [comment]
@andreas-hakansson-ingka :wave: thanks for opening this!  For clarity, does "canonical" here mean the wrong casing or the right casing?  i.e. if the directory's correct casing is `~/code`, which of `git rev-parse` and `package["Dir"]` is returning the expected casing vs `~/codE`

**Comment by andreas-hakansson-ingka** [comment]
@jonabc Oh, sorry about that

- `git rev-parse` returns the correct casing
- `pwd` does not

this can easily be confirmed

Correct
```
mkdir foo
cd FOO
git init
git rev-parse --show-toplevel
pwd
```

**Comment by jonabc** [comment]
@andreas-hakansson-ingka :wave: what OS are your dev machines that you're seeing the problem on, and what version of go are you using?  The fix is simple enough, but I've been unable to reproduce the issue locally in order to write a test case for it :/

**Comment by andreas-hakansson-ingka** [comment]
@jonabc We've been able to reproduce this on both macOS Catalina and Big Sur

**Comment by jonabc** [comment]
@andreas-hakansson-ingka can you set up a repro project? I was able to see the discrepancy from your steps above, but I wasn't able to reproduce the failure in a testing setup.  The fix is pretty minimal but I haven't been able to verify if it works

**Comment by andreas-hakansson-ingka** [comment]
@jonabc not sure how I'd do that? The issue requires you to "cd" into a directory with a path that has a different casing than the one that was used to create it. To add to that, I'm not a Ruby developer either. I know enough to trace down the location of the issue, but I would be terrible at writing actual code 😅 

Or do you want me to create a small Go project, that you can run the fixed version on to verify that it works?

**Comment by jonabc** [comment]
> Or do you want me to create a small Go project, that you can run the fixed version on to verify that it works?

Yes, this would be great.  One thing I'm trying to understand is why/how you're able to hit this on a mac local dev but I can't recreate in tests 😢

**Comment by andreas-hakansson-ingka** [comment]
> One thing I'm trying to understand is why/how you're able to hit this on a mac local dev

Human error. Instead of typing `cd Code` you type `cd code` and you'll be affected by this issue. Not sure how you can repo, because it does require you can do a `cd` operation.

A go sample would only help you verify it manually, not using a test though? So not sure it would add more value than you already being able to reproduce it locally

> I was able to see the discrepancy from your steps above

**Comment by jonabc** [comment]
> A go sample would only help you verify it manually, not using a test though? So not sure it would add more value than you already being able to reproduce it locally

🤷  I've been unable to reproduce the bug locally using multiple different versions of go.  I'll go ahead and merge the linked PR since the change is very localized, shouldn't be harmful, and should resolve the issue.
