### ISSUE TITLE
Ruby license marking as "other"

### ISSUE THREAD

**Issue by AlexWayfer** [github/licensed#382]
Hello.

I'm executing such command:

```
> bundle exec licensed status
...
Errors:
* project.bundler.annotate
  filename: /home/alex/Projects/Work/project/.licenses/bundler/annotate.dep.yml
    - license needs review: other
```

We have such entry in `Gemfile.lock`:

```
annotate (3.1.1)
```

And I'm checking the license of this gem: https://github.com/ctran/annotate_models/blob/v3.1.1/annotate.gemspec#L19

```ruby
s.licenses = ['Ruby']
```

So, I'd like to add `Ruby` as `allowed` license into `.licensed.yaml`, but for some reason it's parsed as `other`.

**Comment by jonabc** [comment]
:wave: hi @AlexWayfer Determinations are made primarily off a dependency's license text and not just the declared license identifier in the package management file.  In this case, it looks like [LICENSE.txt](https://github.com/ctran/annotate_models/blob/v3.1.1/LICENSE.txt) mostly aligns with the standard [ruby license text](https://spdx.org/licenses/Ruby.html)

 That said, this tool isn't directly responsible for making license determinations.  That's done by [licensee](https://github.com/licensee/licensee), which is a better place to follow up.  I'd recommend opening an issue there requesting that they support ruby license text classification and see whether the maintainers there have any feedback or concerns.
 
In the meantime you have two options to get past that specific error
1. manually change the classification at `/home/alex/Projects/Work/project/.licenses/bundler/annotate.dep.yml` from `license: other` to `license: ruby` along with adding `ruby` to the list of allowed licenses in `.licensed.yaml`.
   - as a note, this manual classification will persist so long as the license text provided by the annotate gem does not change
1. mark the `annotate` gem as [reviewed](https://github.com/github/licensed/blob/master/docs/configuration/reviewing_dependencies.md) in `.licensed.yaml`
 
 I'm going to close this for now as there's not really anything that licensed itself can do to help here, but please reopen if you disagree or have any further questions.

**Comment by AlexWayfer** [comment]
> Determinations are made primarily off a dependency's license text and not just the declared license identifier in the package management file. In this case, it looks like [LICENSE.txt](https://github.com/ctran/annotate_models/blob/v3.1.1/LICENSE.txt) mostly aligns with the standard [ruby license text](https://spdx.org/licenses/Ruby.html)

I got it right that `licensed` doesn't take LICENSE text as Ruby License just because of this first line (in Ruby gem, not Ruby itself):

> Ruby is copyrighted free software by Yukihiro Matsumoto <matz@netlab.jp>.

?

**Comment by mlinksva** [comment]
FWIW it would probably not help here if licensee knew about the standard Ruby license text (which it currently doesn't). A copyright sentence and multi-license preamble are usually present and licensee would bail upon seeing the extra text which it could not positively identify as being part of Ruby. There was some discussion in SPDX (which I try to nudge licensee to follow, since that's where the most people focused on license curation are) which seems to have ended at not attempting to account for this variation, see https://github.com/spdx/license-list-XML/issues/837#issuecomment-569966675

**Comment by AlexWayfer** [comment]
My question is still actual and affects my further actions with `licensed`.

**Comment by mlinksva** [comment]
The answer to your question above is no. `licensed` doesn't take the LICENSE text as Ruby License because `licensee` doesn't know about the Ruby License. If it did though, it would probably still not take the LICENSE text as Ruby License because of both the first line, and the dual licensing line, neither of which is part of the Ruby License.

**Comment by AlexWayfer** [comment]
> The answer to your question above is no. `licensed` doesn't take the LICENSE text as Ruby License because `licensee` doesn't know about the Ruby License. If it did though, it would probably still not take the LICENSE text as Ruby License because of both the first line, and the dual licensing line, neither of which is part of the Ruby License.

I don't understand, because closing comment is:



> Determinations are made primarily off a _dependency's license text_ and not just the declared license identifier in the package management file.

So… basing on what determinations about license made in `licensed`? I even don't see such explanation in README, although it seems basic information about "how it works".

**Comment by AlexWayfer** [comment]
I have questions and still wait for answers.
