### ISSUE TITLE
bad link (404) in readme.md - "./docs/configuration/sources.md"

### ISSUE THREAD

**Issue by MrCull** [github/licensed#386]
The following link in the readme.md results in 404 not found error:

"./docs/configuration/sources.md"  --> "https://github.com/github/licensed/blob/master/docs/configuration/sources.md"

I'm not sure what the correct link should be, so thus the issue and not a PR.

This issue was found using tool: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder

**Comment by jonabc** [comment]
thanks for the report 🙇
