### ISSUE TITLE
Empty license for MIT Yarn dependency

### ISSUE THREAD

**Issue by AlexWayfer** [github/licensed#395]
Hello.

I see a lot of errors (from `licensed status`) like this:

```
* yasno.yarn.os-homedir
  filename: /path/to/project/.licenses/yarn/os-homedir.dep.yml, version: 1.0.2, license: , allowed: false
    - cached dependency record not found
```

But I also see this: https://github.com/sindresorhus/os-homedir/blob/v1.0.2/license

![2021-09-07_21-54](https://user-images.githubusercontent.com/6510020/132396533-1d5d35d3-9477-4011-bb1c-55bd898a822b.png)

This is MIT. This is not ``, this is not an empty string, this is MIT.

What is happening with your detection algorithm? This tool seems unusable, I have such… let me count… exactly 1000 errors (from Yarn) for single commercial Ruby on Rails project! WTF? I don't understand. I though your tool is like… leading, most useful, etc., but I see another scenario.

**Comment by jonabc** [comment]
:wave: @AlexWayfer first off, I'm sorry if you're encountering difficulties.  The project you're talking about here with os-homedir comes from that package not distributing it's LICENSE file.  The [files](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#files) configuration only includes [index.js](https://github.com/sindresorhus/os-homedir/blob/b1b0ae70a5965fef7005ff6509a5dd1a78c95e36/package.json#L18-L20).

Licensed works off of locally installed files - if the package chooses not to distribute its LICENSE file then licensed won't be able to detect its license.

> What is happening with your detection algorithm? This tool seems unusable, I have such… let me count… exactly 1000 errors (from Yarn) for single commercial Ruby on Rails project! WTF? I don't understand. I though your tool is like… leading, most useful, etc., but I see another scenario.

If you want to provide a listing of the errors you're facing I'd be happy to help you look into what's going on.  Closing this for now - from the description this is exactly how I'd expect licensed to behave.

**Comment by AlexWayfer** [comment]
> The problem you're seeing with os-homedir comes from that package not distributing it's LICENSE file. The [files](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#files) configuration only includes [index.js](https://github.com/sindresorhus/os-homedir/blob/b1b0ae70a5965fef7005ff6509a5dd1a78c95e36/package.json#L18-L20) which means no other files will be included in local installations.

OK, thank you, sounds reasonable.

So, the `licensed` will never trust `license` field in package description (`package.json`, `.gemspec`)? And no option for this?

**Comment by jonabc** [comment]
Licensed is primarily an aggregation tool that is able to get information from a number of different tools/ecosystems.  Once data is aggregated, classification is performed by [licensee/licensee](https://github.com/github/licensee) which has documentation on [what it looks at](https://github.com/licensee/licensee/blob/master/docs/what-we-look-at.md).

Licensed enables licensee options to look for information from readmes and package manager files.  Licensed also does have some cases where it will auto fill a license if it's not otherwise provided.  I'll take a look at that scenario for os-homedir and let you know if I find anything.

**Comment by jonabc** [comment]
When I run licensed over a minimal reproduction of this issue (package.json only includes a direct dependency on os-homedir@1.0.2), I am seeing the cached metadata include a license file and it's contents.  This was with node 16.3.0, npm 7.18.1, yarn 1.22.11.

What version of node, npm and yarn are you using?  Can you provide a small reproduction project that I can take a look at?
