### ISSUE TITLE
npm list --json doesn't contain 'realPath'

### ISSUE THREAD

**Issue by jonabc** [github/licensed#4]
Found when running licensed with npm v 5.5.1.  It didn't appear that any of the package information out put as part of `npm list --json --production ...` included a [`realPath`](https://github.com/github/licensed/blob/00d9e5db27dea1baf0c7cecadc221fcafc5bf4e8/lib/licensed/source/npm.rb#L31) property.  Instead I was seeing a `path` property.

```
    "array.from": {
      ...
      "path": "/Users/jonabc/.../node_modules/array.from",
      ...
    },
```

`realPath` might have existed for previous npm versions, I can't find good documentation for legacy versions.  However it seems like the `path` property can be used to find the packages unpacked location.

**Comment by kumarmj** [comment]
Hi, I would want to solve this issue. From my understanding path property needs to be added, I would send PR today only

**Comment by kumarmj** [comment]
As I was making sure while reading contributing guide test are running successfully. Results were
`147 runs, 263 assertions, 3 failures, 4 errors, 4 skips` 

1) Failure: Licensed::Source::Pip::enabled?#test_0001_is true if pip source is available [/Users/manoj/opensource/licensed/test/source/pip_test.rb:14]:
Expected nil to be truthy.

2) Failure: Licensed::Command::Cache::with Bower#test_0001_extracts license info [/Users/manoj/opensource/licensed/test/command/cache_test.rb:40]:
Expected false to be truthy

3) Error: Licensed::Source::Pip::dependencies#test_0001_includes direct dependencies:
Errno::ENOENT: No such file or directory - /Users/manoj/opensource/licensed/test/fixtures/pip/venv/bin/pip

 4) Error: Licensed::Source::Pip::dependencies#test_0002_includes indirect dependencies:
Errno::ENOENT: No such file or directory - /Users/manoj/opensource/licensed/test/fixtures/pip/venv/bin/pip

 5) Failure: Licensed::Command::List::with Bower#test_0001_lists dependencies [/Users/manoj/opensource/licensed/test/command/list_test.rb:31]:
Expected /Found jquery/ to match "Displaying dependencies for bower\n  bower dependencies:\n  * bower dependencies: 0\n".

 6) Error: Licensed::Command::List::with Cabal#test_0001_lists dependencies:
TypeError: no implicit conversion of nil into String

7) Error: Licensed::Command::Cache::with Cabal#test_0001_extracts license info:
TypeError: no implicit conversion of nil into String

**Comment by jonabc** [comment]
@kumarmj 👋 thanks for taking a look at this!

Does it change anything to run `bundle exec 'rake setup[-f]'` before `bundle exec rake test`?  I've noticed that the contributing docs don't mention the `bundle exec` part, I'll update the documentation to include `bundle exec` 👍 

Would you mind also helping me understand what tools/languages you have installed in your development environment?
- [ ] npm
- [ ] ruby/bundler
- [ ] cabal
- [ ] bower
- [ ] pip
- [ ] go
- [ ] go + dep

**Comment by kumarmj** [comment]
Solved errors, it was becuase I had not installed cabal or bower or go & dep. I created pull request, let me know if changes are correct or some other changes are required.

**Comment by jonabc** [comment]
@kumarmj I'll take a look at the errors, you shouldn't need to have all of the tools installed to be able to run the tests - they should skip when you don't have the required tools installed.

**Comment by jonabc** [comment]
Fixed by https://github.com/github/licensed/pull/60
