### ISSUE TITLE
Licenses are not found 

### ISSUE THREAD

**Issue by mmorel-35** [github/licensed#408]
Hi! I have tried to use licensed on golang project where those dependencies are present :
* https://github.com/xeipuuv/gojsonpointer
* https://github.com/xeipuuv/gojsonschema
* https://github.com/xeipuuv/gojsonreference

They all are maintained by the same owner and the licenses are named the same way : LICENSE-APACHE-2.0.txt

The problem is that this file is not found by licensed.
There are already PR to rename the file but there is no answer from the owner.

**Comment by jonabc** [comment]
@mmorel-35 :wave: this is a question better asked in [licensee/licensee](https://github.com/licensee/licensee).  This project is primarily responsible for sourcing all dependencies for a project with enough information for licensee to detect what license is in use.  The determination of which files contain valid license info, and any classification based on the file contents, is done by licensee 🙏
