### ISSUE TITLE
yarn: Support 2/3 (berry)

### ISSUE THREAD

**Issue by clinejj** [github/licensed#419]
Was looking into updating our rails app to use Yarn 2/3 (specifically Yarn 3), and the current yarn integration doesn't work given some of the commands have changed or are no longer supported.

Given the incompatibility, it might make sense to add yarn berry support as a separate package type. The new commands:

`yarn list` has become `yarn info`, which supports some of the same command line parameters but not all (specifically `-s`, `--no-progress`, and `--production`): https://yarnpkg.com/cli/info

`yarn licenses list` was removed, but re-added with this plugin that again offers some of the parameters but not all (specifically `-s` and `--no-progress`) : https://github.com/mhassan1/yarn-plugin-licenses

I also didn't check whether the output of the two new commands matched yarn 1, so there may need to be a slight update to parsing.

**Comment by jonabc** [comment]
@clinejj thanks for opening this up.

the plugin shouldn't be necessary, licensed was only using the `yarn licenses` command to find the package homepage url.  it looks like that info is available with `yarn info --manifest`. 

my only hesitancy about creating a separate package type is the user story around migration.  if users migrate from yarn v1 to yarn v2+ and do not manually move files around then there is the potential for manual curation to be lost.

Let me know if you have thoughts about how this could be accomplished to not give too much grief to users migrating from yarn v1->v2+.  I'm going to think about this as well and might try to get support worked out during the long weekend in the US.

**Comment by clinejj** [comment]
@jonabc that's a good point, I was thinking more from the licensed side than the migration story. In that case, it would probably make more sense to update https://github.com/github/licensed/blob/master/lib/licensed/sources/yarn.rb to check for which version (1, or 2+) of yarn is installed and then use the appropriate commands/parsing.

Something else I noticed, the `yarn.rb` also assumes `node_modules` exists to generate the dependency path, which may not be the case for a [PnP setup](https://yarnpkg.com/features/pnp) which stores them in the `pnp.cjs` zip file or the `.yarn/cache` folder. `yarn info --cache` does print the cache path, so running `yarn info --manifest --cache` would get the package homepage and the path to the dependency locally.

**Comment by jonabc** [comment]
I was thinking about this after posting ☝️ and I think we can manage keeping two separate implementations by
1. have each implementation return `yarn` from the class' `type` method
1. have each implementation check for the appropriate version in the `enabled?` method

Having multiple sources with the same type that are mutually exclusive at runtime based on the return value of `enabled?` seems like a decent strategy in general for sources that need to change over time based on source versioning.

PnP is interesting and doesn't fit well generally with the strategy for "all files must exist on disk" that is currently required by the underlying license classification tool `licensee`.  WDYT about keeping this task limited to basic support for `node_modules` installations and iterating for future changes such as PnP support?

**Comment by clinejj** [comment]
That seems like a good way to handle the different yarn versions, keeping the license generation separate from the storage of the information.

Agree that it would make sense to support `node_modules` for now and iterate to support for PnP

**Comment by jonabc** [comment]
Opened https://github.com/github/licensed/pull/423 as an approach for basic support for multiple yarn handlers
