### ISSUE TITLE
licensed cache failing with JSON::ParserError

### ISSUE THREAD

**Issue by markstanley-nps** [github/licensed#436]
Running licensed cache is failing with a JSON parse error while processing the yarn dependencies

```
C:/Ruby30-x64/lib/ruby/3.0.0/json/common.rb:216:in `parse': 809: unexpected token at '{ (JSON::ParserError)
'
        from C:/Ruby30-x64/lib/ruby/3.0.0/json/common.rb:216:in `parse'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/licensed-3.4.0/lib/licensed/sources/yarn/v1.rb:85:in `block in dependency_paths'
```

The underlying cause is a test that has been added to the resolve npm module to check it handles an invalid package dependency. (https://github.com/browserify/resolve/blob/067db38df700632c4de505f31537400c8185dae1/test/resolver/malformed_package_json/package.json)

Should licensed handle the invalid package.json by ignoring it and not including in the dependency paths. If this was a valid dependency then an error would be raised later as below as the dependency could not be found

```
Error xxx (0.1.0)

  * Errors:
    * yyyy.yarn.xxxx
      - dependency path not found
```

Is there another solution?

**Comment by jonabc** [comment]
@markstanley-nps :wave: this problem was [previously reported](https://github.com/github/licensed/issues/430) and [licensed version 3.4.1](https://github.com/github/licensed/releases/tag/3.4.1) was released this past Friday as a fix.  Please upgrade to latest and let me know if you continue to see this 🙏 

Thank you for opening an issue in the browserify repo to possibly fix this on their end too!

**Comment by markstanley-nps** [comment]
Thanks the latest version fixes the issue and thanks for the quick turn around of a fix

**Comment by ljharb** [comment]
If a tool, like a license scanner, is operating on third party code (like in node_modules) it is objectively incorrect for it to assume that a) it’s well-formed/valid and b) that the user can easily fix it, which means that failing unrecoverably is a bug. Additionally, a license tool should never be checking package.jsons that aren’t at the top level of a package boundary.

A better additional fix beyond #341 would be restricting package.json lookups to the subset that are eligible to contain licenses, which this particular one is not.

**Comment by jonabc** [comment]
@ljharb I'd be happy to discuss the merits of different solutions.  this tool has to deal with all sorts of variations while being limited by the commands available by package manager or language tools, and in this case while I would love to agree with you those capabilities just don't exist AFAIK to allow for your objectively correct criteria.

**Comment by ljharb** [comment]
I’m not sure why - if a package.json’s path doesn’t match `**/node_modules/*/package.json` or `**/node_modules/@*/*/package.json`, then you ignore it.

**Comment by jonabc** [comment]
@ljharb so I'm clearly not an npm or yarn expert here, but this enumeration source deals with yarn v1.x, which AFAIK has nests dependencies under when two or more versions of the same dependency are used in the dependency tree in a project.  The test fixtures in this project include such a case where graceful-fs @4.2.8 and @3.0.12 are both used.

So searching one level deep will result in missed dependencies and is not a viable option as far as I can tell.

**Comment by ljharb** [comment]
Yarn works identically to npm here. Note the ** in my pseudoglob; it should match with any amount of nesting, and would still have excluded this particular file.

**Comment by jonabc** [comment]
Fantastic, I'll look at a change then.  I'm not opinionated on the code.

As feedback though, there are better ways to relay the information than how you chose to do so.  I'd appreciate a softer and more human focused tone in the future if you have more to say.  This project is not my day job and being told "you are objectively wrong" while giving subjective opinions on your own project make me not want to be an OSS maintainer.  This is a community and I shouldn't be feeling attacked in any sort of reasonable conversation.

**Comment by ljharb** [comment]
Thanks for the feedback, I’ll try to incorporate it in the future.
