### ISSUE TITLE
"Other" is not a clickable option when looking Licenses breakdown

### ISSUE THREAD

**Issue by ghostsquad** [github/licensed#454]
## Repro

```
https://github.com/orgs/<myorg>/insights/dependencies
```

![image](https://user-images.githubusercontent.com/903488/153308977-46b62c30-63b7-4835-82dd-d55eb8b153d3.png)

**Comment by jonabc** [comment]
:wave: Hi @ghostsquad this repo/project doesn't power the view that you're describing here.  I'd recommend reaching out to [GitHub support](https://support.github.com/) with any questions or feedback, I can't do anything about the issue you're facing here 😢
