### ISSUE TITLE
found the wrong notices from file containing "legal"

### ISSUE THREAD

**Issue by kk-zu** [github/licensed#509]
## version
3.7.0

## details
Dependent on [@fortawesome/free-solid-svg-icons](https://www.npmjs.com/package/@fortawesome/free-solid-svg-icons) (npm) , `licensed cache` make `notices` from `faLegal.js` and `faLegal.d.ts`. I think they should not be considered "LEGAL".

Thank you in advance for your consideration.

**Comment by jonabc** [comment]
:wave: @kk-zu thanks for the report, I should have the [fix](https://github.com/github/licensed/pull/510) out in a new release either today or tomorrow
