### ISSUE TITLE
Error when npm package readme is utf-8 encoded: "readme_file.rb:42:in `match': invalid byte sequence in US-ASCII (ArgumentError)"

### ISSUE THREAD

**Issue by cnaslain** [github/licensed#51]
Hi,

I continue to play with licensed under docker...

I encounter an issue when I add **uuid** to my package.json file. Here are the necessary files to reproduce this behaviour:

.licensed.yaml
```
name: 'placement-back'
cache_path: '/app/test2/.licenses'
source_path: '/app/test2'
sources:
  npm: true
allowed:
  - mit
```

package.json 
```
{
  "name": "placement-back",
  "version": "0.0.0",
  "dependencies": {
    "uuid": "^3.2.1"
  }
}
```

And the commands/output within my docker image:
```
$ cd /app/test2
$ npm update -f
$ licensed cache
Caching licenses for placement-back:
  npm dependencies:
/usr/local/bundle/gems/licensed-1.1.0/lib/licensed/shell.rb:17:in `execute': command exited with status 1 (Licensed::Shell::Error)
  npm list --parseable --production --long
    npm ERR! missing: uuid@^3.2.1, required by placement-back@0.0.0
	from /usr/local/bundle/gems/licensed-1.1.0/lib/licensed/source/npm.rb:66:in `npm_list_command'
	from /usr/local/bundle/gems/licensed-1.1.0/lib/licensed/source/npm.rb:55:in `package_location_command'
	from /usr/local/bundle/gems/licensed-1.1.0/lib/licensed/source/npm.rb:23:in `dependencies'
	from /usr/local/bundle/gems/licensed-1.1.0/lib/licensed/command/cache.rb:29:in `block (3 levels) in run'
	from /usr/local/bundle/gems/licensed-1.1.0/lib/licensed/command/cache.rb:20:in `map'
	from /usr/local/bundle/gems/licensed-1.1.0/lib/licensed/command/cache.rb:20:in `block (2 levels) in run'
	from /usr/local/bundle/gems/licensed-1.1.0/lib/licensed/command/cache.rb:17:in `chdir'
	from /usr/local/bundle/gems/licensed-1.1.0/lib/licensed/command/cache.rb:17:in `block in run'
	from /usr/local/bundle/gems/licensed-1.1.0/lib/licensed/command/cache.rb:12:in `each'
	from /usr/local/bundle/gems/licensed-1.1.0/lib/licensed/command/cache.rb:12:in `flat_map'
	from /usr/local/bundle/gems/licensed-1.1.0/lib/licensed/command/cache.rb:12:in `run'
	from /usr/local/bundle/gems/licensed-1.1.0/lib/licensed/cli.rb:48:in `run'
	from /usr/local/bundle/gems/licensed-1.1.0/lib/licensed/cli.rb:17:in `cache'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /usr/local/bundle/gems/licensed-1.1.0/exe/licensed:5:in `<top (required)>'
	from /usr/local/bundle/bin/licensed:23:in `load'
	from /usr/local/bundle/bin/licensed:23:in `<main>'
```

I think this occurs when the README.md file is utf-8 encoded; I also see this behaviour for other packages.

I'm not sure this is a licensed bug; maybe a licensee bug as the error occurs in `/usr/local/bundle/gems/licensee-9.9.1/lib/licensee/project_files/readme_file.rb:42` file?

As a workaround; I simply seach and overwrite all README/AUTHORS files with an empty content:
```
	find . -type f -name "README.md" -exec bash -c "echo > '{}'" \;
	find . -type f -name "Readme.md" -exec bash -c "echo > '{}'" \;
	find . -type f -name "readme.md" -exec bash -c "echo > '{}'" \;
	find . -type f -name "AUTHORS" -exec bash -c "echo > '{}'" \;
```

Then if I re-run the licensed command:
```
$ licensed cache
Caching licenses for placement-back:
  npm dependencies:
    Caching uuid (3.2.1)
License caching complete!
* placement-back npm dependencies: 1
```

Without (utf-8) content, it works; but I guess this is not a good workaround.

Any idea for a better process?

Regards,

Chris

**Comment by jonabc** [comment]
:wave: @cnaslain glad to see things are still moving along.

It looks like the error you posted is from a missing package, e.g. not having run `npm install` first.  Since the issue is about utf-8 encoded content I'm assuming this is the wrong stack trace and you already got past that 👍 

There's a long term and a (probable) short term fix for this.

Long term: If you have the time and are feeling up to it, you can fix this in `licensee`!  This was reported in `licensee` [awhile back](https://github.com/benbalter/licensee/issues/102) but it looks like the fix was never followed up on and didn't make it into the gem.

Short term:  Try adding `ENV LANG C.UTF-8` to your Dockerfile.  That's fixed what I think is the same issue for me, when I was playing around with docker + licensed 😄

**Comment by cnaslain** [comment]
@jonabc Thanks for the tip! Adding `ENV LANG C.UTF-8` to my dockerfile did the job :-)
