### ISSUE TITLE
Cocoapods-core is incompatible with Rails 7

### ISSUE THREAD

**Issue by codez** [github/licensed#609]
We use licensed in our Rails 7 application. When trying to upgrade to licensed 4.0.1, `bundle update` returns the following error:

```bash
Because licensed >= 4.0.0 depends on cocoapods-core = 1.11.3
  and cocoapods-core >= 1.11.0.beta.1 depends on activesupport >= 5.0, < 7,
  licensed >= 4.0.0 requires activesupport >= 5.0, < 7.
Thus, licensed >= 4.0.0 is incompatible with railties >= 7.0.0.
So, because Gemfile depends on railties ~> 7.0
  and Gemfile depends on licensed > 4.0,
  version solving has failed.
```

It seems that with the addition of cocoapods, an unwanted restriction on the activesupport version was introduced.

Or is there any known workaround?

**Comment by jonabc** [comment]
@codez thanks for the report. I'll take a look!  Is using licensed 4.x a critical upgrade or can you stick with 3.x while I dig in?  Just looking to understand the priority of getting this fixed 🙏

**Comment by jonabc** [comment]
I don't think there's any way around the version conflict.  I opened a PR on CocoaPods/Core to update the max version requirement to `< 8`.  If that's accepted by the project maintainers I'll put out a new release of licensed with the fix when possible.
