### ISSUE TITLE
Add a version command

### ISSUE THREAD

**Issue by sridharavinash** [github/licensed#62]
Now that we have a binary build with `ruby-packer` it would be nice to have a 
```
licensed --version
```
which would display the current version of the binary.
This could be useful for applications that want to download and run the `licensed` binary and automatically update to the latest version if available.
 for .eg
```
licensed --update-licensed
```
would update the current copy is there's a later release version of the binary otherwise continue using the locally cached version.

Does that make sense?

**Comment by dideler** [comment]
I believe this can be closed now.

```
$ licensed version
1.5.2

$ licensed --version
1.5.2
```

**Comment by jonabc** [comment]
@sridharavinash I'm closing this issue (agree with ☝️ ).

> `licensed --update-licensed`

It will be hard to scope down which update the user wants based on the scenario of usage.  Does the user want the latest patch update?  minor release? etc.

It might also cause headaches if not used properly and the pulled update contains breaking changes.

I think this is better left to manual interaction or bespoke automation built for specific scenarios.  If you still think this is worth investigating, please open a separate issue 🙇
