### ISSUE TITLE
Go modules license detection seems off (possibly /v2)

### ISSUE THREAD

**Issue by dangoor** [github/licensed#622]
licensed is listing other as the license for `github.com/github/go-spdx/v2/spdxexp`, but `github.com/github/go-spdx` has an [MIT license](https://github.com/github/go-spdx/blob/main/LICENSE).

**Comment by jonabc** [comment]
:wave: @dangoor can you provide the contents of the metadata file that licensed has created?

**Comment by dangoor** [comment]
lol I think I see the problem. This particular project has a file called [license.go](https://github.com/github/go-spdx/blob/main/spdxexp/license.go), which contains every SPDX ID and licensed is, pretty reasonably I think, seeing that as "other".
