### ISSUE TITLE
Add support for pnpm as a source

### ISSUE THREAD

**Issue by rwwagner90** [github/licensed#625]
```
Caching dependency records for ember-app
  npm
  * 0 npm dependencies
/usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/sources/npm.rb:162:in `dig': String does not have #dig method (TypeError)

        parent&.dig("_dependencies", name) || peer_dependency(parent, name)
                    ^^^^^^^^^^^^^^^^^^^^^
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/sources/npm.rb:162:in `extract_version'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/sources/npm.rb:74:in `block in recursive_dependencies'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/sources/npm.rb:68:in `each'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/sources/npm.rb:68:in `recursive_dependencies'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/sources/npm.rb:77:in `block in recursive_dependencies'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/sources/npm.rb:68:in `each'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/sources/npm.rb:68:in `recursive_dependencies'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/sources/npm.rb:77:in `block in recursive_dependencies'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/sources/npm.rb:68:in `each'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/sources/npm.rb:68:in `recursive_dependencies'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/sources/npm.rb:77:in `block in recursive_dependencies'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/sources/npm.rb:68:in `each'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/sources/npm.rb:68:in `recursive_dependencies'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/sources/npm.rb:52:in `packages'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/sources/npm.rb:31:in `enumerate_dependencies'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/sources/source.rb:89:in `cached_dependencies'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/sources/source.rb:72:in `dependencies'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/commands/command.rb:136:in `run_source'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/commands/cache.rb:54:in `run_source'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/commands/command.rb:101:in `block (2 levels) in run_app'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/commands/command.rb:98:in `map'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/commands/command.rb:98:in `block in run_app'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/commands/command.rb:95:in `chdir'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/commands/command.rb:95:in `run_app'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/commands/cache.rb:40:in `block in run_app'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/commands/cache.rb:166:in `with_licensee_configuration'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/commands/cache.rb:39:in `run_app'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/commands/command.rb:67:in `block in run_command'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/commands/command.rb:64:in `map'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/commands/command.rb:64:in `run_command'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/commands/cache.rb:24:in `run_command'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/commands/command.rb:23:in `run'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/cli.rb:115:in `run'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/lib/licensed/cli.rb:18:in `cache'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /usr/local/Cellar/licensed/4.0.4/libexec/gems/licensed-4.0.4/exe/licensed:5:in `<top (required)>'
	from /usr/local/Cellar/licensed/4.0.4/libexec/bin/licensed:25:in `load'
	from /usr/local/Cellar/licensed/4.0.4/libexec/bin/licensed:25:in `<main>'
```

I see it says `0 npm dependencies` which is odd. Perhaps there is an issue since we are using pnpm?

**Comment by jonabc** [comment]
> Perhaps there is an issue since we are using pnpm?

That would be my initial guess.  I've only used pnpm a handful of times and I'm not terribly familiar with how it interacts with npm during package management, if it interacts at all.

1. What version of npm and pnpm are you using?
1. Can you provide the dependencies and devDependencies sections of your package.json so I can try to repro locally?

**Comment by rwwagner90** [comment]
@jonabc using pnpm at all should be sufficient to reproduce. I just created a new package with `npm init` and added just one dep of `ember-cli` and I can reproduce the error.

```yml
sources:
  npm: true

allowed:
  - mit
  - isc
  - bsd
  - bsd-2-clause
  - bsd-3-clause
  - wtfpl
  - apache-2.0
  - cc0-1.0
  ```

pnpm `7.26.3`
npm `6.14.17`

**Comment by rwwagner90** [comment]
You will have to `pnpm I --shamefully-hoist` to get pnpm to hoist packages rather than using all symlinks.

**Comment by rwwagner90** [comment]
Also, FYI there is a `pnpm licenses ls` command which will list all the licenses, so perhaps we could leverage that here?

**Comment by rwwagner90** [comment]
Looks like something like `pnpm licenses list --long --json` gives us deps grouped by license types in JSON format. Could we add a source that parses that?

**Comment by jonabc** [comment]
> Looks like something like pnpm licenses list --long --json gives us deps grouped by license types in JSON format. Could we add a source that parses that?

I took a look and wow this is the first time I've seen a package manager provide exactly the information that's needed by this tool 😂 .  A new source sounds like a good idea, I'll take a look when I get a chance but in the immediate future I'll look to fix the underlying issue with the npm source.

**Comment by jonabc** [comment]
🤔 scratch the previous comment, I think pnpm might generally just be incompatible with npm CLI commands?  whether I `pnpm install` using `--shamefully-hoist` or not, `npm list --all --json --production --long` is returning a ton of errors from what pnpm is reporting as optional dependencies.  I'll try to get to creating the pnpm source sooner rather than later

I'm using npm `8.5.0` and pnpm `7.26.3`

**Comment by rwwagner90** [comment]
@jonabc you want to use pnpm commands, not npm ones. `pnpm licenses list --long --json --prod` would be the pnpm equivalent of what you are trying to run with npm I think. I think we should add a new source that runs the pnpm commands.

**Comment by jonabc** [comment]
@rwwagner90 yep, I was trying to resolve the original issue from this ticket that talks about the npm source raising an error.  the npm source doesn't use any pnpm commands

**Comment by rwwagner90** [comment]
@jonabc fair enough. I'm not sure if it is possible to make the `npm` source work here though, so we should focus on `pnpm`. Anything I can do to help? I don't really know ruby myself, so I don't think I would have much luck implementing the source myself.

**Comment by jonabc** [comment]
@rwwagner90 I hear you on the pnpm source and agree that it's the best solution to the current problem.  I'm just a little strapped for time.  I'll try to get something put together over the next few days.

**Comment by rwwagner90** [comment]
@jonabc is there anything we can do to be helpful in the meantime? Some of my colleagues know ruby pretty well, so perhaps we could get a PR up, but if you already know exactly what you would do here, perhaps it would be better to wait. Just let us know how we can best help!

**Comment by jonabc** [comment]
@rwwagner90 if you're able to hold tight for me to get the basic structure in place that would be best.  pnpm should be one of the easier package managers to integrate, but it would still probably go faster if I put in the base of the integration.  once that's done I'd love any extra eyes or help with any edge cases, bugs, or improvements that come up.

is pnpm support blocking anything critical for you?

**Comment by rwwagner90** [comment]
@jonabc not super critical. I've spent the past couple weeks getting pnpm up and running on our repos. Now all the tests are passing and such, but we're unable to run license checks, so it is blocking somewhat, but not critical.

**Comment by jonabc** [comment]
@rwwagner90 I've got the basics of a source up at https://github.com/github/licensed/pull/626.  As mentioned in the PR the only real quirk I found with pnpm was that the cli doesn't return data only for a specific workspace.  The `pnpm licenses list` command is still not finalized though according to the documentation so it's possible that is coming soon 🤷 .  It should be easy to incorporate workspaces similar to the npm source if/when the pnpm CLI supports it.

**Comment by rwwagner90** [comment]
Awesome, thank you so much for the quick turnaround!

**Comment by jonabc** [comment]
yes it is coming, I'm working through some other changes to include in the release and should have a release out today.

**Comment by jonabc** [comment]
Ah sorry I missed documenting a difference between the npm and pnpm sources.  With the pnpm source, you'll need to specify dependencies in the configuration file as `<name>@<version>`.  This is eventually going to be the norm for all dependencies in a future major version bump, and the pnpm source is being used to lead the way and uncover any issues related to that change.

**Comment by rwwagner90** [comment]
@jonabc thanks for the info! Does the version support globs or semver strings or anything? Like `foo@*` or `foo@^6.0.0` etc

**Comment by jonabc** [comment]
@RobbieTheWagner I've added support for version matching in https://github.com/github/licensed/pull/629.  Note that version range matching uses Ruby's semver support which is a little different than node's semver package.  I've updated the [ignoring](https://github.com/github/licensed/blob/reviewed-and-ignored-at-versions/docs/configuration/ignoring_dependencies.md#ignoring-dependencies-at-specific-versions) and [reviewing](https://github.com/github/licensed/blob/reviewed-and-ignored-at-versions/docs/configuration/reviewing_dependencies.md#reviewing-dependencies-at-specific-versions) docs in that PR with some usage hints including links to Ruby's documentation on semver support.
