### ISSUE TITLE
Regression in 1.2.0

### ISSUE THREAD

**Issue by AlanFoster** [github/licensed#71]
Hi, I noticed a regression between version 1.2.0 and 1.1.0 when trying to run `licensed status` on a project which has a dependency on `libv8`:

> /Users/User/.rvm/gems/ruby-2.5.1/gems/licensed-1.2.0/lib/licensed/source/bundler.rb:74:in `block in specs_for_dependencies': Unable to find a specification for libv8 (>= 6.3) in any sources (RuntimeError)

This error happens on both a mac + ubuntu with v1.2.0, but does _not_ happen on v1.1.0

----

### Replicating

With the following Gemfile:

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "mini_racer"
```

Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    libv8 (6.7.288.46.1)
    mini_racer (0.2.0)
      libv8 (>= 6.3)

PLATFORMS
  ruby

DEPENDENCIES
  mini_racer

BUNDLED WITH
   1.16.1
```

`.licensed.yml`

```
sources:
  rubygem: true
```

Running the following with licensed 1.2.0 currently fails:

```
licensed status
```

### Version 1.2.0

```
/Users/User/.rvm/gems/ruby-2.5.1/gems/licensed-1.2.0/lib/licensed/source/bundler.rb:74:in `block in specs_for_dependencies': Unable to find a specification for libv8 (>= 6.3) in any sources (RuntimeError)
```

### Version 1.1.0

```
licensed status
Checking licenses for example: 3 dependencies
FFF

Warnings:

/private/tmp/example/.licenses/rubygem/bundler.txt:
  - cached license data missing

/private/tmp/example/.licenses/rubygem/libv8.txt:
  - cached license data missing

/private/tmp/example/.licenses/rubygem/mini_racer.txt:
  - cached license data missing

3 dependencies checked, 3 warnings found.
```

### Extra debugging

I can see that `licensed` is trying to check the following `spec_path` locations:

```
/Users/user/.rvm/gems/ruby-2.5.1/specifications/mini_racer-0.2.0.gemspec
/Users/user/.rvm/gems/ruby-2.5.1/specifications/libv8-6.7.288.46.1.gemspec
```

It's dying currently dying on libv8, but I can tell that the `gemspec` actually has an extra operating system extension that `licensed` wasn't expecting:

```
$ ls /Users/user/.rvm/gems/ruby-2.5.1/specifications/ | grep libv8
libv8-6.7.288.46.1-x86_64-darwin-16.gemspec
```

The file name extension is slightly different on Ubuntu too.

**Comment by jonabc** [comment]
:wave: I'm getting ready to release the next version of licensed and wanted to clear up the regression ASAP.  I've opened https://github.com/github/licensed/pull/72 as a small fix to find a specification object that contains platform information, so that the platform will be included in `spec.full_name`
