### ISSUE TITLE
Optionally include non-production dependencies

### ISSUE THREAD

**Issue by mlinksva** [github/licensed#8]
Dependency sources currently exclude non-production dependencies, e.g.:

https://github.com/github/licensed/blob/d39cae6bb5dfccfd3df9bd847de73618690b419e/lib/licensed/source/npm.rb#L55

https://github.com/github/licensed/blob/d39cae6bb5dfccfd3df9bd847de73618690b419e/lib/licensed/source/bundler.rb#L36-L39

It might be good to have an option to include all dependencies, should a user wish to use licensed to track development dependencies as well as production.

**Comment by jonabc** [comment]
As a note, the bundler source was updated to support including non-production dependencies  in https://github.com/github/licensed/pull/54.  This is shipped as part of the 1.2.0 release.
