### ISSUE TITLE
npm dependencies can overwrite their own licenses

### ISSUE THREAD

**Issue by jclem** [github/licensed#87]
With npm, it is possible to have two different versions of the same dependency at the same time, with two potentially different licenses.

For example, given dependencies "a", "b", and "c", where "a" depends on "b@0.0.1" and "c" depends on "b@0.0.2", npm will essentially have a tree in `node_modules` that looks like this:

```
               ┌──────────┐               
               │          │               
               │   app    │               
               │          │               
               └──────────┘               
                     │                    
      ┌──────────────┼──────────────┐     
      ▼              ▼              ▼     
┌──────────┐   ┌──────────┐   ┌──────────┐
│          │   │          │   │          │
│    a     │   │ b@0.0.1  │   │    c     │
│          │   │          │   │          │
└──────────┘   └──────────┘   └──────────┘
                                    │     
                                    │     
                                    ▼     
                              ┌──────────┐
                              │          │
                              │ b@0.0.2  │
                              │          │
                              └──────────┘
```

However, when caching licenses for these dependencies, only the latest version encountered while traversing the dependency tree will be kept—in this case, "b@0.0.2"'s license will overwrite "b@0.0.1"'s.

**Comment by jonabc** [comment]
@jclem good catch.  To fix this requires separating the `name` metadata of the package from the file name/path used to cache the metadata.  An open PR for sourcing Git Submodules had the same potential problem and takes the steps to alleviate this.

Once that PR is merged, we can fix this in npm and cache metadata for multiple versions of a dependency separately  🎉

**Comment by jonabc** [comment]
Git submodule PR: https://github.com/github/licensed/pull/86
