### ISSUE TITLE
`npm list` should not limit to `--production`

### ISSUE THREAD

**Issue by jclem** [github/licensed#90]
I assume even in development, we are still bound by the licenses included npm packages, but not sure how much we care.

In launch-editor, for example, we still use these dependencies in our "production" environment as part of the build process, but they're not distributed to the user. That said, a savvy developer could still look at our output JavaScript and see, for example, that [typescript](https://github.com/github/launch-editor/blob/6c980efcb148c12a97f855454472c5eb76442af9/package.json#L123) was used in our build process.

**Comment by mlinksva** [comment]
There's an existing issue #8 to make ignoring non-production dependencies an option. But ignoring them is a reasonable default as most users are concerned about their obligations when distributing software.
